In [2]:
import numpy as np
import pandas as pd
import math
import networkx as nx
import matplotlib.pyplot as plt
import random
from community import community_louvain  # python-louvain kütüphanesi gerekli
from sklearn.cluster import SpectralClustering
from sklearn.metrics import silhouette_score
import scipy.linalg as la
from statistics import mode
import numpy as np
import leidenalg
import igraph as ig
from collections import defaultdict
from sklearn.metrics import adjusted_rand_score
from sklearn.metrics import normalized_mutual_info_score
from scipy.special import comb  # binom için
from collections import defaultdict
from networkx.algorithms.community import girvan_newman
from networkx.algorithms.community.centrality import girvan_newman
from itertools import islice

In [3]:

#df_combined= pd.read_csv('2022America.csv')
#df_combined= pd.read_csv("2022Asia.csv")
#df_combined= pd.read_csv('2022Europe.csv')



#df_combined= pd.read_csv('25usa.csv')
#df_combined=  pd.read_csv("25Asia.csv")
#df_combined= pd.read_csv('25Africa.csv')
#df_combined=  pd.read_csv('25europa.csv')
df_combined=  pd.read_csv('22all.csv')
#df_combined=  pd.read_csv('25all.csv')

In [4]:
df_combined

,0,Skill_1,Skill_2,Skill_3,Skill_4,Skill_5,Skill_6,Skill_7,Skill_8,Skill_9,...,Skill_41,Skill_42,Skill_43,Skill_44,Skill_45,Skill_46,Skill_47,Skill_48,Skill_49,Skill_50
0,Graphic Design\r\nAdobe Photoshop\r\nBanner Ad...,Graphic Design,Adobe Photoshop,Banner Ad Design,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Balance Sheet\r\nCash Flow Statement\r\nQuickb...,Balance Sheet,Cash Flow Statement,Quickbooks,Accounting Basics,Bookkeeping,Shopify,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Graphic Design\r\nWeb Development\r\nWeb Design,Graphic Design,Web Development,Web Design,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Adobe Photoshop Elements\r\nRAW\r\nAdobe Photo...,Adobe Photoshop Elements,RAW,Adobe Photoshop,Image Editing,Photo Manipulation,Photo Editing,People,Portrait Art,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Apache Airflow\r\nMySQL\r\nPython\r\nMachine L...,Apache Airflow,MySQL,Python,Machine Learning,RESTful API,Python Numpy FastAI,Deep Neural Network,Apache Solr,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14995,Spring Boot\r\nJava\r\nJavaScript,Spring Boot,Java,JavaScript,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14996,Animated Environment\r\n3D Sculpting\r\nAutode...,Animated Environment,3D Sculpting,Autodesk 3ds Max,Blender,Character Design,Animation,3D Animation,Motion Graphics,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14997,Video Editing\r\nAdobe Premiere Pro\r\nVideo P...,Video Editing,Adobe Premiere Pro,Video Post-Editing,Video Intro & Outro,YouTube Development,Video Production,Adobe After Effects,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14998,Network Security\r\nMalware,Network Security,Malware,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14999,Microsoft Windows\r\nSystem Administration\r\n...,Microsoft Windows,System Administration,Windows Server,Microsoft Active Directory,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [8]:
from collections import Counter

# Kolon isimlerini string olarak kontrol et
skill_columns = [col for col in df_combined.columns if str(col).startswith("Skill_")]

# Tüm becerileri topla
all_skills = []
for col in skill_columns:
    all_skills.extend(df_combined[col].dropna().tolist())

# Sayım
skill_counts = Counter(all_skills)

# En çoktan en aza sırala
most_common_skills = skill_counts.most_common()

# Sonuçları yazdır
print("🔝 En sık geçen kalifikasyonlar:")
for skill, count in most_common_skills:
    print(f"{skill}: {count} kez")

🔝 En sık geçen kalifikasyonlar:
Graphic Design: 1288 kez
Content Writing: 1281 kez
English: 1160 kez
Web Development: 1103 kez
JavaScript: 1000 kez
Social Media Marketing: 967 kez
Web Design: 934 kez
WordPress: 850 kez
Researcher: 790 kez
Data Entry: 783 kez
Lead Generation: 744 kez
Search Engine Optimization: 639 kez
Adobe Photoshop: 619 kez
Facebook: 618 kez
Video Editing: 616 kez
HTML: 600 kez
CSS: 600 kez
Instagram: 588 kez
Copywriting: 585 kez
Virtual Assistant: 573 kez
Writing: 570 kez
PHP: 541 kez
Marketing Strategy: 525 kez
Android: 524 kez
Social Media Management: 513 kez
Adobe Illustrator: 494 kez
Creative Writing: 490 kez
Article Writing: 478 kez
Python: 448 kez
Video Production: 433 kez
Mobile App Development: 431 kez
API: 411 kez
Microsoft Excel: 399 kez
Communications: 398 kez
Facebook Advertising: 366 kez
Blog Content: 358 kez
SEO Writing: 351 kez
Translation: 350 kez
iOS: 347 kez
Android App Development: 346 kez
Logo Design: 339 kez
Shopify: 337 kez
Google Ads: 336 kez
Administrative Support: 327 kez
Email Communication: 321 kez
Blog Writing: 313 kez
Illustration: 311 kez
Sales: 310 kez
Google Analytics: 310 kez
Customer Service: 305 kez
SEO Keyword Research: 304 kez
API Integration: 297 kez
Social Media Content Creation: 296 kez
Java: 291 kez
Smartphone: 290 kez
Market Research: 288 kez
Landing Page: 276 kez
Social Media Content: 271 kez
Social Media Advertising: 270 kez
Proofreading: 270 kez
Video Post-Editing: 269 kez
React: 268 kez
Adobe After Effects: 262 kez
Adobe Premiere Pro: 257 kez
Web Application: 252 kez
Article: 248 kez
Virtual Assistance: 238 kez
HTML5: 232 kez
Node.js: 229 kez
Business with 1-9 Employees: 215 kez
Scheduling: 211 kez
Data Scraping: 211 kez
3D Modeling: 209 kez
Email Marketing: 206 kez
MySQL: 204 kez
Internet Marketing: 203 kez
Videography: 201 kez
SEO Backlinking: 197 kez
Photo Editing: 194 kez
Campaign Management: 193 kez
Cold Calling: 184 kez
Website: 179 kez
3D Design: 177 kez
List Building: 176 kez
Motion Graphics: 173 kez
Animation: 171 kez
Voice Acting: 168 kez
Voice-Over: 167 kez
Explainer Video: 167 kez
German: 165 kez
Data Analysis: 162 kez
3D Rendering: 161 kez
WooCommerce: 158 kez
SQL: 156 kez
Website Content: 153 kez
On-Page SEO: 153 kez
Social Media Imagery: 152 kez
Brand Identity & Guidelines: 152 kez
TikTok: 151 kez
Ghostwriting: 149 kez
iOS Development: 149 kez
Audio Editing: 145 kez
Male: 144 kez
Editing & Proofreading: 138 kez
Pay Per Click Advertising: 137 kez
YouTube: 134 kez
Amazon Web Services: 133 kez
Organic Traffic Growth: 133 kez
Outbound Sales: 132 kez
Accounting: 130 kez
Telemarketing: 128 kez
PPC Campaign Setup & Management: 128 kez
Native: 128 kez
C#: 127 kez
US English Dialect: 126 kez
Data Mining: 125 kez
Female: 125 kez
Prospect List: 125 kez
Automation: 124 kez
Video Commercial: 124 kez
Microsoft Word: 122 kez
Off-Page SEO: 120 kez
Influencer Marketing: 119 kez
Project Management: 119 kez
Fashion & Beauty: 118 kez
Mockup: 117 kez
Facebook Ads Manager: 116 kez
2D Animation: 116 kez
Customer Support: 116 kez
Layout Design: 115 kez
Figma: 114 kez
Email Campaign Setup: 113 kez
Architectural Design: 113 kez
Photography: 112 kez
Adobe InDesign: 111 kez
Editor: 109 kez
Bookkeeping: 108 kez
Infographic: 107 kez
Flutter: 107 kez
Retargeting: 106 kez
Typing: 106 kez
Mobile App Design: 105 kez
Real Estate: 103 kez
Phone Communication: 102 kez
French: 101 kez
Kotlin: 100 kez
React Native: 99 kez
Shopify Templates: 99 kez
Wireframing: 99 kez
WordPress Plugin: 98 kez
Print Design: 98 kez
Responsive Design: 98 kez
Final Cut Pro X: 97 kez
LinkedIn: 96 kez
Campaign Optimization: 96 kez
Education: 95 kez
Image Editing: 95 kez
YouTube Marketing: 95 kez
Tech & IT: 95 kez
User Interface Design: 95 kez
TypeScript: 94 kez
Autodesk AutoCAD: 93 kez
Market Analysis: 93 kez
Character Design: 92 kez
SEO Performance: 92 kez
C++: 91 kez
Scriptwriting: 90 kez
Accuracy Verification: 89 kez
SEO Audit: 89 kez
B2B Marketing: 88 kez
Machine Learning: 88 kez
Database: 88 kez
Content Creation: 87 kez
Data Visualization: 86 kez
Search Engine Marketing: 85 kez
Drawing: 85 kez
3D Animation: 84 kez
Ecommerce: 84 kez
Digital Marketing: 83 kez
User Flow: 83 kez
Tablet: 83 kez
Prototyping: 82 kez
Personal Administration: 81 kez
Data Extraction: 80 kez
Microsoft PowerPoint: 80 kez
Google Docs: 79 kez
HubSpot: 79 kez
Legal: 79 kez
Interior Design: 79 kez
CSS 3: 79 kez
Game Development: 79 kez
DevOps: 79 kez
Business with 10-99 Employees: 78 kez
Laravel: 78 kez
Ecommerce Website: 77 kez
Health & Wellness: 77 kez
Competitive Analysis: 77 kez
Linux: 76 kez
Scripting: 76 kez
Blockchain: 75 kez
Unity: 75 kez
Presentation Design: 74 kez
Sales & Marketing: 74 kez
Video Intro & Outro: 74 kez
RESTful API: 74 kez
Microsoft Windows: 73 kez
General Transcription: 73 kez
Spanish: 72 kez
Email Support: 72 kez
Phone Support: 72 kez
Photo Retouching: 72 kez
Ebook Writing: 72 kez
System Administration: 69 kez
Wix: 69 kez
Ebook: 69 kez
Google Tag Manager: 69 kez
Cryptocurrency: 69 kez
MongoDB: 68 kez
Executive Support: 68 kez
Business Writing: 68 kez
Instagram Story: 68 kez
Canva: 67 kez
Dropshipping: 67 kez
Firebase: 66 kez
Shopify Theme: 65 kez
Custom PHP: 64 kez
CAD: 63 kez
Product Photography: 63 kez
Business Analysis: 63 kez
Amazon FBA: 62 kez
jQuery: 62 kez
Conversion Rate Optimization: 62 kez
Relationship Management: 62 kez
Network Administration: 62 kez
Data Science: 62 kez
User Experience Design: 62 kez
API Development: 62 kez
Ecommerce Platform Development: 62 kez
Residential Design: 61 kez
Technical Writing: 61 kez
Docker: 61 kez
Content Marketing Strategy: 61 kez
Git: 60 kez
Content SEO: 60 kez
Marketing Automation: 60 kez
Swift: 60 kez
Financial Analysis: 60 kez
Functional Testing: 60 kez
In-App Purchases: 60 kez
Game Design: 59 kez
Business Presentation: 59 kez
Topic Research: 59 kez
Amazon: 59 kez
Web Testing: 59 kez
.NET Framework: 59 kez
Camera: 59 kez
Elementor: 58 kez
TikTok Ad: 58 kez
Retail & Consumer Goods: 58 kez
Webflow: 57 kez
Finance & Accounting: 57 kez
Academic Writing: 57 kez
Sourcing: 57 kez
TikTok Marketing: 57 kez
Legal Consulting: 56 kez
Food & Beverage: 56 kez
Social Media Marketing Strategy: 56 kez
Business Development: 56 kez
Legal Writing: 55 kez
Electrical Engineering: 55 kez
File Management: 55 kez
Photo Manipulation: 55 kez
Website Redesign: 54 kez
Fact-Checking: 54 kez
Banner Ad Design: 54 kez
Middle-Aged Adult: 54 kez
Angular: 54 kez
Hybrid App Development: 54 kez
Bank Reconciliation: 54 kez
Product Design: 53 kez
Network Security: 53 kez
Customer Relationship Management: 53 kez
Dutch: 52 kez
Artificial Intelligence: 52 kez
Error Detection: 52 kez
Manual Testing: 52 kez
Branding: 51 kez
Contract Law: 51 kez
Product Listings: 51 kez
Statistics: 50 kez
Price & Quote Negotiation: 50 kez
User Authentication: 50 kez
Content Strategy: 50 kez
Database Development: 50 kez
Redux: 50 kez
Mathematics: 49 kez
Email Automation: 49 kez
YouTube Development: 49 kez
Technical SEO: 49 kez
Recruiting: 49 kez
Google Sheets: 49 kez
Corporate Brand Identity: 49 kez
Business Plan: 48 kez
Linux System Administration: 48 kez
Company Research: 48 kez
Balance Sheet: 47 kez
Chinese: 47 kez
Amazon Webstore: 47 kez
Customer Satisfaction: 47 kez
Presentations: 47 kez
Shopify Apps: 47 kez
Time Management: 47 kez
Appointment Setting: 46 kez
Blender: 46 kez
Audio Production: 46 kez
Tax Preparation: 46 kez
Accounting Basics: 46 kez
WordPress Development: 46 kez
PostgreSQL: 46 kez
Italian: 46 kez
Unreal Engine: 45 kez
UX & UI: 45 kez
Mobile App Testing: 45 kez
Travel & Hospitality: 45 kez
British English Accent: 45 kez
Vue.js: 44 kez
Ad Copy: 44 kez
People: 44 kez
Public Relations: 44 kez
Content Localization: 44 kez
Software QA: 44 kez
Critical Thinking Skills: 44 kez
Interpersonal Skills: 43 kez
Architectural Rendering: 43 kez
Partnership Development: 43 kez
Cartoon Art: 43 kez
Display Ad: 43 kez
Adobe XD: 43 kez
Financial Accounting: 43 kez
Twitter: 42 kez
Business Planning & Strategy: 42 kez
Media & Entertainment: 42 kez
2D Design: 42 kez
Concept Design: 42 kez
Clothing: 42 kez
Brand Guidelines: 42 kez
Electronics: 42 kez
English to German Translation: 42 kez
Minimalist: 42 kez
Financial Modeling: 41 kez
Japanese: 41 kez
Social Media Account Setup: 41 kez
Microsoft Office: 41 kez
Norwegian: 41 kez
Sketch: 41 kez
Pinterest: 40 kez
Brochure: 40 kez
Microsoft Azure: 40 kez
Online Chat Support: 40 kez
User Profile Creation: 40 kez
Business Services: 40 kez
Young Adult: 40 kez
CI/CD: 39 kez
Marketing Analytics: 39 kez
Brand Identity Design: 39 kez
Intuit QuickBooks: 39 kez
Kubernetes: 39 kez
Media Relations: 39 kez
Script: 39 kez
Candidate Sourcing: 38 kez
Testimonial Video: 38 kez
Fluent: 38 kez
Stripe: 38 kez
Documentary: 38 kez
Django: 38 kez
Lighting: 38 kez
Python Script: 38 kez
Communication Etiquette: 38 kez
Business: 37 kez
Lead Generation Analysis: 37 kez
ASP.NET: 37 kez
Microsoft SQL Server: 37 kez
Fiction: 37 kez
Marketing: 37 kez
Floor Plan Design: 37 kez
Sales Development: 37 kez
PDF Conversion: 37 kez
Brand Positioning: 37 kez
Romance: 36 kez
Sports & Recreation: 36 kez
Squarespace: 36 kez
Quickbooks: 36 kez
Narration: 36 kez
Video Advertising: 36 kez
Fiction Writing: 36 kez
Nonfiction: 36 kez
PCB Design: 36 kez
Amazon PPC: 36 kez
Arabic: 36 kez
Copy Editing: 35 kez
Affiliate Marketing: 35 kez
Legal Research: 35 kez
Qualitative Research: 35 kez
Mechanical Engineering: 35 kez
Autodesk 3ds Max: 35 kez
Database Architecture: 35 kez
Automated Testing: 34 kez
Amazon Seller Central: 34 kez
Inventory Management: 34 kez
Golang: 34 kez
AngularJS: 34 kez
Acting: 34 kez
SketchUp: 34 kez
Software Testing: 34 kez
Desktop Application: 34 kez
Bug Reports: 34 kez
Database Design: 34 kez
Mobile App Localization: 34 kez
Mobile UI Design: 34 kez
A/B Testing: 34 kez
Resume Writing: 33 kez
English to Spanish Translation: 33 kez
Book: 33 kez
Algorithm Development: 33 kez
Product Management: 33 kez
Audience Segmentation & Targeting: 33 kez
Concept Artistry: 33 kez
Candidate Interviewing: 33 kez
Usability Testing: 33 kez
Color Grading: 33 kez
Visual Communication: 33 kez
Electronic Design: 33 kez
Email Copywriting: 32 kez
Agile Project Management: 32 kez
Bootstrap: 32 kez
SaaS: 32 kez
Russian: 32 kez
Social Media Strategy: 32 kez
Project Scheduling: 32 kez
Microsoft Power BI: 31 kez
Candidate Evaluation: 31 kez
Pitchbook: 31 kez
Human Resource Management: 31 kez
Thai: 31 kez
Product Knowledge: 31 kez
Circuit Design: 30 kez
Commercial Design: 30 kez
Windows Server: 30 kez
Online Research: 30 kez
Interaction Design: 30 kez
Drafting: 30 kez
Novel: 30 kez
File Maintenance: 30 kez
Ethereum: 30 kez
Twitter Marketing: 30 kez
Contemporary Style: 30 kez
Manufacturing & Construction: 29 kez
Dashboard: 29 kez
CRM Software: 29 kez
Information Security: 29 kez
Office 365: 29 kez
Advertising Design: 29 kez
Google Chrome Extension: 29 kez
Embedded System: 29 kez
Task Coordination: 29 kez
Audio Transcription: 29 kez
Amazon EC2: 29 kez
Press Release: 29 kez
Startup Company: 29 kez
Deep Learning: 29 kez
Web Crawling: 28 kez
Computer Vision: 28 kez
Website Customization: 28 kez
GoDaddy: 28 kez
Campaign Setup: 28 kez
Portuguese: 28 kez
MATLAB: 28 kez
Lead Generation Strategy: 28 kez
Android Studio: 28 kez
Commenting: 28 kez
Apple Xcode: 28 kez
Advertisement: 27 kez
Mailchimp: 27 kez
Native App Development: 27 kez
Packaging Design: 27 kez
SEO Setup & Configuration: 27 kez
CRM Automation: 27 kez
Web Scraping: 27 kez
LinkedIn Recruiting: 27 kez
PDF: 27 kez
LinkedIn Campaign Manager: 27 kez
Storytelling: 27 kez
Content Marketing: 26 kez
Ubuntu: 26 kez
2D Art: 26 kez
Formatting: 26 kez
HR & Business Services: 26 kez
Social Media Video: 26 kez
Front-End Development: 26 kez
Accounting Software: 26 kez
Forex Trading: 26 kez
LinkedIn Development: 26 kez
Solidity: 26 kez
Strategy: 26 kez
Spring Boot: 26 kez
Campaign Reporting: 26 kez
MySQL Programming: 26 kez
Ruby on Rails: 25 kez
R: 25 kez
Tax Law: 25 kez
AWS Lambda: 25 kez
Visual Basic for Applications: 25 kez
Virtual Reality: 25 kez
Research Methods: 25 kez
Logistics Management: 25 kez
Product Development: 25 kez
Jira: 25 kez
Near-Native: 25 kez
Thai to English Translation: 25 kez
Elearning: 25 kez
Freestyle Drawing: 25 kez
Cover Letter Writing: 24 kez
Computer Skills: 24 kez
Digital Project Management: 24 kez
Documentation: 24 kez
Screenwriting: 24 kez
Photorealistic Rendering: 24 kez
Resume: 24 kez
Health & Fitness: 24 kez
Magento: 24 kez
Blockchain Architecture: 24 kez
Sales Management: 24 kez
Visual Effects: 23 kez
Google Search Console: 23 kez
Accounts Receivable: 23 kez
Lead Generation Content Creation: 23 kez
Business with 100-999 Employees: 23 kez
Figma Expert: 23 kez
Bug Fix: 23 kez
Zapier: 23 kez
Community Management: 23 kez
Autodesk Maya: 23 kez
Mobile Advertising: 23 kez
English to French Translation: 23 kez
Community Engagement: 23 kez
Swedish: 23 kez
Google Cloud Platform: 23 kez
Smart Contract: 23 kez
Scrapy: 23 kez
SEO Strategy: 23 kez
Covers & Packaging: 23 kez
Product Roadmap: 23 kez
Test Case Design: 23 kez
Book Writing: 23 kez
Book Cover: 22 kez
Draft Documentation: 22 kez
Live Interpretation: 22 kez
Administrative Assistant: 22 kez
Contract Drafting: 22 kez
Salesforce CRM: 22 kez
Corporate Video: 22 kez
CPA: 22 kez
ExpressJS: 22 kez
Software: 22 kez
Fashion Design: 22 kez
Network Equipment: 22 kez
Podcast: 22 kez
About Us Page: 22 kez
CodeIgniter: 22 kez
Music Video: 22 kez
Microcontroller Programming: 22 kez
Chat & Messaging Software: 22 kez
NodeJS Framework: 22 kez
Candidate Recommendation: 22 kez
Hindi: 22 kez
Natural Language Processing: 22 kez
Bitcoin: 22 kez
American English Accent: 22 kez
Machine Learning Model: 21 kez
Ruby: 21 kez
Next.js: 21 kez
Bug Tracking & Reports: 21 kez
ClickFunnels: 21 kez
Music Production: 21 kez
Email Marketing Strategy: 21 kez
Data Cleansing: 21 kez
Biography: 21 kez
Civil Engineering: 21 kez
Lead Nurturing: 21 kez
Data Analytics: 21 kez
Website Asset: 21 kez
Microservice: 21 kez
Polish: 21 kez
Moodle: 21 kez
Financial Projection: 21 kez
Dart: 21 kez
Mobile Game: 21 kez
Corporate Law: 21 kez
2D Design & Drawings: 21 kez
Product Description: 20 kez
Supply Chain & Logistics: 20 kez
Facebook Pixel Setup & Optimization: 20 kez
Accounts Payable: 20 kez
Structural Engineering: 20 kez
Ahrefs: 20 kez
Klaviyo: 20 kez
Casual Tone: 20 kez
Software Design: 20 kez
Bot Development: 20 kez
App Development: 20 kez
MetaTrader 4: 20 kez
Colorful Style: 20 kez
Report: 20 kez
Legal Assistance: 20 kez
Academic Editing: 20 kez
Advertising Strategy: 20 kez
Style Guide: 20 kez
Career Coaching: 20 kez
Order Tracking: 20 kez
Google Suite: 20 kez
SEO Content: 20 kez
Social Media Account Integration: 20 kez
Location-Based Service: 20 kez
Google Shopping: 19 kez
Page Speed Optimization: 19 kez
Engineering & Architecture: 19 kez
Ethical Hacking: 19 kez
Autodesk Revit: 19 kez
Creative Strategy: 19 kez
Caption: 19 kez
SolidWorks: 19 kez
Paralegal: 19 kez
Castilian Spanish: 19 kez
Landscape Design: 19 kez
Zoho CRM: 19 kez
Art & Design: 19 kez
Business with 1000+ Employees: 19 kez
Vector Graphic: 19 kez
Xero: 19 kez
Cover Art Design: 19 kez
Adobe Photoshop Lightroom: 19 kez
Flutter Developer: 19 kez
Computer Network: 19 kez
Construction: 19 kez
Email Design: 19 kez
Analytics: 19 kez
Photo Slideshow: 18 kez
API Testing: 18 kez
Sales Funnel Copywriting: 18 kez
Chemistry: 18 kez
DaVinci Resolve: 18 kez
SQLite: 18 kez
ERP Software: 18 kez
Custom Graphics: 18 kez
Engineering Design: 18 kez
Narrative: 18 kez
German to English Translation: 18 kez
Essay Writing: 18 kez
Amazon S3: 18 kez
Poster: 18 kez
Jenkins: 18 kez
.NET Core: 18 kez
Purchase Orders: 18 kez
Sales Writing: 18 kez
Deployment Automation: 18 kez
Blockchain Development: 18 kez
Objective-C: 18 kez
Plugin Development: 18 kez
Supplier Search: 17 kez
JPG: 17 kez
Inbound Inquiry: 17 kez
Headline: 17 kez
Augmented Reality: 17 kez
Email & Newsletter: 17 kez
XML: 17 kez
Intellectual Property Law: 17 kez
2D Illustration: 17 kez
Microsoft Active Directory: 17 kez
Label & Package Design: 17 kez
Data Engineering: 17 kez
Azure DevOps: 17 kez
Sketching: 17 kez
Pinterest Ads Manager: 17 kez
Learning Management System: 17 kez
PayPal: 17 kez
Database Administration: 17 kez
Turkish: 17 kez
Business Translation: 17 kez
Contact List: 17 kez
Ebook Design: 17 kez
Security Analysis: 17 kez
Photo Color Correction: 17 kez
Brand Identity: 17 kez
Business Intelligence: 17 kez
Google Apps Script: 16 kez
ActiveCampaign: 16 kez
Social Media Lead Generation: 16 kez
Drupal: 16 kez
Visualization: 16 kez
Forecasting: 16 kez
Sound Mixing: 16 kez
Selenium: 16 kez
Human Body: 16 kez
Buying: 16 kez
Instructional Design: 16 kez
Software Development: 16 kez
Project Plans: 16 kez
Audience Research: 16 kez
Requirement Analysis: 16 kez
WordPress SEO Plugins: 16 kez
English to Italian Translation: 16 kez
Danish: 16 kez
JSON: 16 kez
Digital Marketing Strategy: 16 kez
Vulnerability Assessment: 16 kez
Medical Transcription: 16 kez
Magento 2: 16 kez
Sales Analytics: 16 kez
Image Processing: 16 kez
NGINX: 16 kez
Resume Screening: 16 kez
TensorFlow: 16 kez
Microsoft Visual Studio: 16 kez
GitHub: 16 kez
Supply Chain Management: 16 kez
Quality Assurance: 16 kez
Payment Functionality: 16 kez
AWS Application: 16 kez
Compositing: 15 kez
English to Chinese Translation: 15 kez
Microsoft Outlook: 15 kez
Content Rewriting: 15 kez
Media Buying: 15 kez
Maxon Cinema 4D: 15 kez
Yoast SEO: 15 kez
Account Reconciliation: 15 kez
UX Research: 15 kez
Medical Billing & Coding: 15 kez
Limited Liability Company: 15 kez
Singing: 15 kez
Partnership Agreement: 15 kez
PHP Script: 15 kez
Website Optimization: 15 kez
Brand Strategy: 15 kez
Portrait Art: 15 kez
Media Pitch: 15 kez
Icon Design: 15 kez
Quantitative Research: 15 kez
Sales Presentation: 15 kez
Decision Making: 15 kez
App Store Optimization: 15 kez
CAD Drafting: 15 kez
Google Data Studio: 15 kez
Canadian English Dialect: 15 kez
Brand Research: 15 kez
Energetic Tone: 15 kez
Mobile App: 15 kez
Tax Return: 15 kez
Technical Support: 15 kez
Big Data: 15 kez
ETL Pipeline: 15 kez
Communication Skills: 15 kez
Technical Manual: 15 kez
Content Moderation: 15 kez
Process Infographics: 15 kez
Case Studies: 15 kez
Mechanical Design: 15 kez
Map Integration: 15 kez
phpMyAdmin: 15 kez
Alibaba Sourcing: 15 kez
Creative Direction: 15 kez
Instagram Ad Campaign: 15 kez
Payment Gateway Integration: 14 kez
Spring Framework: 14 kez
Growth Analytics: 14 kez
WebRTC: 14 kez
Landscaping: 14 kez
Design Enhancement: 14 kez
Browser Extension: 14 kez
Digital Illustration: 14 kez
Marketing Audit: 14 kez
Travel Planning: 14 kez
Customer Acquisition: 14 kez
Executive Summary: 14 kez
Flask: 14 kez
Marketing Campaign Setup & Implementation: 14 kez
Pipedrive: 14 kez
Brand Marketing: 14 kez
Etsy Listing: 14 kez
How To: 14 kez
Tailwind CSS: 14 kez
Amazon Listing Optimization: 14 kez
Content Development: 14 kez
Arduino: 14 kez
Subtitles: 14 kez
Press Distribution: 14 kez
Ansible: 14 kez
Push Notifications: 14 kez
Customer Acquisition Strategy: 14 kez
Technical Recruiter: 14 kez
Back-End Development: 14 kez
Anime: 14 kez
English to Japanese Translation: 14 kez
Email Template Development: 14 kez
Voice Recording: 14 kez
Performance Testing: 14 kez
Statistical Analysis: 14 kez
WordPress Theme: 14 kez
Data Modeling: 14 kez
PySpark: 14 kez
Social Media Ad Campaign: 14 kez
MP4: 13 kez
In-App Advertising: 13 kez
Research Papers: 13 kez
Platform Plugin: 13 kez
Blog: 13 kez
PPTX: 13 kez
Firebase Cloud Firestore: 13 kez
Form Completion: 13 kez
Source File: 13 kez
Client Management: 13 kez
Email Deliverability: 13 kez
3D Texturing: 13 kez
Calming Tone: 13 kez
Neural Network: 13 kez
Urdu: 13 kez
Informational Infographic: 13 kez
In-App Search: 13 kez
Website Copywriting: 13 kez
Audio Post Production: 13 kez
Candidate Management: 13 kez
Microsoft Dynamics 365: 13 kez
Bluetooth: 13 kez
NFT: 13 kez
iOS Developer: 13 kez
Server: 13 kez
Chinese to English Translation: 13 kez
Furniture Design: 13 kez
Quantitative Analysis: 13 kez
Transcription Timestamping: 13 kez

In [10]:
Network = pd.DataFrame(most_common_skills, columns=["Skill", "Frekans"])

# Sonuç kontrolü
print(Network.head())

             Skill  Frekans
0   Graphic Design     1288
1  Content Writing     1281
2          English     1160
3  Web Development     1103
4       JavaScript     1000

In [12]:
Network["ID"]=range(len(Network))
Network

                       Skill  Frekans    ID
0             Graphic Design     1288     0
1            Content Writing     1281     1
2                    English     1160     2
3            Web Development     1103     3
4                 JavaScript     1000     4
...                      ...      ...   ...
3801        Article Spinning        1  3801
3802              Green Card        1  3802
3803               Trade Law        1  3803
3804  Amicus Amicus Attorney        1  3804
3805        Oregon State Bar        1  3805

[3806 rows x 3 columns]

In [14]:
# 1. Skill isimleriyle tam sayı (int) ID'leri eşleştiren sözlük oluştur
skill_to_id = dict(zip(Network["Skill"], Network["ID"].astype(int).astype(str)))

# 2. Skill kolonlarını seç
skill_columns = [col for col in df_combined.columns if str(col).startswith("Skill_")]

# 3. Her hücredeki beceriyi ID ile değiştir ve NaN yerine boş string ver
for col in skill_columns:
    df_combined[col] = df_combined[col].map(skill_to_id).fillna('').astype(str).replace('nan', '')

In [16]:
df_combined

,0,Skill_1,Skill_2,Skill_3,Skill_4,Skill_5,Skill_6,Skill_7,Skill_8,Skill_9,...,Skill_41,Skill_42,Skill_43,Skill_44,Skill_45,Skill_46,Skill_47,Skill_48,Skill_49,Skill_50
0,Graphic Design\r\nAdobe Photoshop\r\nBanner Ad...,0,12,274,,,,,,,...,,,,,,,,,,
1,Balance Sheet\r\nCash Flow Statement\r\nQuickb...,305,1128,391,316,136,41,,,,...,,,,,,,,,,
2,Graphic Design\r\nWeb Development\r\nWeb Design,0,3,6,,,,,,,...,,,,,,,,,,
3,Adobe Photoshop Elements\r\nRAW\r\nAdobe Photo...,1488,1121,12,156,271,78,327,744,,...,,,,,,,,,,
4,Apache Airflow\r\nMySQL\r\nPython\r\nMachine L...,2310,74,28,170,204,3548,2284,2463,,...,,,,,,,,,,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14995,Spring Boot\r\nJava\r\nJavaScript,504,53,4,,,,,,,...,,,,,,,,,,
14996,Animated Environment\r\n3D Sculpting\r\nAutode...,1116,1200,404,313,163,85,176,84,,...,,,,,,,,,,
14997,Video Editing\r\nAdobe Premiere Pro\r\nVideo P...,14,63,60,203,297,29,62,,,...,,,,,,,,,,
14998,Network Security\r\nMalware,280,2129,,,,,,,,...,,,,,,,,,,
14999,Microsoft Windows\r\nSystem Administration\r\n...,205,212,447,677,,,,,,...,,,,,,,,,,

In [18]:
# Skill_ kolonlarını seç
skill_columns = [col for col in df_combined.columns if str(col).startswith("Skill_")]

# Yeni bir kolon oluştur: Tüm Skill_ID'leri virgül ile birleştir
df_combined["Skill_ID_List"] = df_combined[skill_columns].apply(
    lambda row: ",".join([str(val) for val in row if val != '']), axis=1
)
# Sonucu göster
print(df_combined[["Skill_ID_List"]].head())

                       Skill_ID_List
0                           0,12,274
1            305,1128,391,316,136,41
2                              0,3,6
3    1488,1121,12,156,271,78,327,744
4  2310,74,28,170,204,3548,2284,2463

In [20]:
data = df_combined["Skill_ID_List"].dropna().tolist()

In [22]:
data= [row for row in data if any(c not in ' \t\n\r' for c in row)]
#data

In [24]:
# Kenar ağırlıklarını saklamak için sözlük
edge_weights = {}

for row in data:
    # Satırdaki düğümleri al (tekrarları ve boşlukları temizle)
    row_nodes = [int(node.strip()) for node in row.split(",")]
    
    # Tüm düğüm çiftleri için kenar oluştur (fully connected)
    for i in range(len(row_nodes)):
        for j in range(i + 1, len(row_nodes)):
            # Kenarı sıralı şekilde sakla (yönlü olmayan graf)
            edge = tuple(sorted((row_nodes[i], row_nodes[j])))
            
            # Kenar ağırlığını güncelle (varsa +1, yoksa 1 ata)
            if edge in edge_weights:
                edge_weights[edge] += 1
            else:
                edge_weights[edge] = 1

# Düğümleri bul (kenarlardan otomatik çıkar)
nodes = set()
for edge in edge_weights:
    nodes.add(edge[0])
    nodes.add(edge[1])

# NetworkX ağırlıklı graf oluştur
import networkx as nx
G = nx.Graph()

# Düğümleri ekle
G.add_nodes_from(nodes)

# Kenarları ve ağırlıklarını ekle
for edge, weight in edge_weights.items():
    G.add_edge(edge[0], edge[1], weight=weight)

# Graf bilgilerini yazdır
print("Düğümler:", G.nodes())
print("Kenarlar ve Ağırlıklar:")
for u, v, data in G.edges(data=True):
    print(f"{u}-{v}: weight={data['weight']}")

Düğümler: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190, 191, 192, 193, 194, 195, 196, 197, 198, 199, 200, 201, 202, 203, 204, 205, 206, 207, 208, 209, 210, 211, 212, 213, 214, 215, 216, 217, 218, 219, 220, 221, 222, 223, 224, 225, 226, 227, 228, 229, 230, 231, 232, 233, 234, 235, 236, 237, 238, 239, 240, 241, 242, 243, 244, 245, 246, 247, 248, 249, 250, 251, 252, 253, 254, 255, 256, 257, 258, 259, 260, 261, 262, 263, 264, 265, 266, 267, 268, 269, 270, 271, 272, 273, 274, 275, 276, 277, 278, 279, 280, 281, 282, 283, 284, 285, 286, 287, 288, 289, 290, 291, 292, 293, 294, 295, 296, 297, 298, 299, 300, 301, 302, 303, 304, 305, 306, 307, 308, 309, 310, 311, 312, 313, 314, 315, 316, 317, 318, 319, 320, 321, 322, 323, 324, 325, 326, 327, 328, 329, 330, 331, 332, 333, 334, 335, 336, 337, 338, 339, 340, 341, 342, 343, 344, 345, 346, 347, 348, 349, 350, 351, 352, 353, 354, 355, 356, 357, 358, 359, 360, 361, 362, 363, 364, 365, 366, 367, 368, 369, 370, 371, 372, 373, 374, 375, 376, 377, 378, 379, 380, 381, 382, 383, 384, 385, 386, 387, 388, 389, 390, 391, 392, 393, 394, 395, 396, 397, 398, 399, 400, 401, 402, 403, 404, 405, 406, 407, 408, 409, 410, 411, 412, 413, 414, 415, 416, 417, 418, 419, 420, 421, 422, 423, 424, 425, 426, 427, 428, 429, 430, 431, 432, 433, 434, 435, 436, 437, 438, 439, 440, 441, 442, 443, 444, 445, 446, 447, 448, 449, 450, 451, 452, 453, 454, 455, 456, 457, 458, 459, 460, 461, 462, 463, 464, 465, 466, 467, 468, 469, 470, 471, 472, 473, 474, 475, 476, 477, 478, 479, 480, 481, 482, 483, 484, 485, 486, 487, 488, 489, 490, 491, 492, 493, 494, 495, 496, 497, 498, 499, 500, 501, 502, 503, 504, 505, 506, 507, 508, 509, 510, 511, 512, 513, 514, 515, 516, 517, 518, 519, 520, 521, 522, 523, 524, 525, 526, 527, 528, 529, 530, 531, 532, 533, 534, 535, 536, 537, 538, 539, 540, 541, 542, 543, 544, 545, 546, 547, 548, 549, 550, 551, 552, 553, 554, 555, 556, 557, 558, 559, 560, 561, 562, 563, 564, 565, 566, 567, 568, 569, 570, 571, 572, 573, 574, 575, 576, 577, 578, 579, 580, 581, 582, 583, 584, 585, 586, 587, 588, 589, 590, 591, 592, 593, 594, 595, 596, 597, 598, 599, 600, 601, 602, 603, 604, 605, 606, 607, 608, 609, 610, 611, 612, 613, 614, 615, 616, 617, 618, 619, 620, 621, 622, 623, 624, 625, 626, 627, 628, 629, 630, 631, 632, 633, 634, 635, 636, 637, 638, 639, 640, 641, 642, 643, 644, 645, 646, 647, 648, 649, 650, 651, 652, 653, 654, 655, 656, 657, 658, 659, 660, 661, 662, 663, 664, 665, 666, 667, 668, 669, 670, 671, 672, 673, 674, 675, 676, 677, 678, 679, 680, 681, 682, 683, 684, 685, 686, 687, 688, 689, 690, 691, 692, 693, 694, 695, 696, 697, 698, 699, 700, 701, 702, 703, 704, 705, 706, 707, 708, 709, 710, 711, 712, 713, 714, 715, 716, 717, 718, 719, 720, 721, 722, 723, 724, 725, 726, 727, 728, 729, 730, 731, 732, 733, 734, 735, 736, 737, 738, 739, 740, 741, 742, 743, 744, 745, 746, 747, 748, 749, 750, 751, 752, 753, 754, 755, 756, 757, 758, 759, 760, 761, 762, 763, 764, 765, 766, 767, 768, 769, 770, 771, 772, 773, 774, 775, 776, 777, 778, 779, 780, 781, 782, 783, 784, 785, 786, 787, 788, 789, 790, 791, 792, 793, 794, 795, 796, 797, 798, 799, 800, 801, 802, 803, 804, 805, 806, 807, 808, 809, 810, 811, 812, 813, 814, 815, 816, 817, 818, 819, 820, 821, 822, 823, 824, 825, 826, 827, 828, 829, 830, 831, 832, 833, 834, 835, 836, 837, 838, 839, 840, 841, 842, 843, 844, 845, 846, 847, 848, 849, 850, 851, 852, 853, 854, 855, 856, 857, 858, 859, 860, 861, 862, 863, 864, 865, 866, 867, 868, 869, 870, 871, 872, 873, 874, 875, 876, 877, 878, 879, 880, 881, 882, 883, 884, 885, 886, 887, 888, 889, 890, 891, 892, 893, 894, 895, 896, 897, 898, 899, 900, 901, 902, 903, 904, 905, 906, 907, 908, 909, 910, 911, 912, 913, 914, 915, 916, 917, 918, 919, 920, 921, 922, 923, 924, 925, 926, 927, 928, 929, 930, 931, 932, 933, 934, 935, 936, 937, 938, 939, 940, 941, 942, 943, 944, 945, 946, 947, 948, 949, 950, 951, 952, 953, 954, 955, 956, 957, 958, 959, 960, 961, 962, 963, 964, 965, 966, 967, 968, 969, 970, 971, 972, 973, 974, 975, 976, 977, 978, 979, 980, 981, 982, 983, 984, 985, 986, 987, 988, 989, 990, 991, 992, 993, 994, 995, 996, 997, 998, 999, 1000, 1001, 1002, 1003, 1004, 1005, 1006, 1007, 1008, 1009, 1010, 1011, 1012, 1013, 1014, 1015, 1016, 1017, 1018, 1019, 1020, 1021, 1022, 1023, 1024, 1025, 1026, 1027, 1028, 1029, 1030, 1031, 1032, 1033, 1034, 1035, 1036, 1037, 1038, 1039, 1040, 1041, 1042, 1043, 1044, 1045, 1046, 1047, 1048, 1049, 1050, 1051, 1052, 1053, 1054, 1055, 1056, 1057, 1058, 1059, 1060, 1061, 1062, 1063, 1064, 1065, 1066, 1067, 1068, 1069, 1070, 1071, 1072, 1073, 1074, 1075, 1076, 1077, 1078, 1079, 1080, 1081, 1082, 1083, 1084, 1085, 1086, 1087, 1088, 1089, 1090, 1091, 1092, 1093, 1094, 1095, 1096, 1097, 1098, 1099, 1100, 1101, 1102, 1103, 1104, 1105, 1106, 1107, 1108, 1109, 1110, 1111, 1112, 1113, 1114, 1115, 1116, 1117, 1118, 1119, 1120, 1121, 1122, 1123, 1124, 1125, 1126, 1127, 1128, 1129, 1130, 1131, 1132, 1133, 1134, 1135, 1136, 1137, 1138, 1139, 1140, 1141, 1142, 1143, 1144, 1145, 1146, 1147, 1148, 1149, 1150, 1151, 1152, 1153, 1154, 1155, 1156, 1157, 1158, 1159, 1160, 1161, 1162, 1163, 1164, 1165, 1166, 1167, 1168, 1169, 1170, 1171, 1172, 1173, 1174, 1175, 1176, 1177, 1178, 1179, 1180, 1181, 1182, 1183, 1184, 1185, 1186, 1187, 1188, 1189, 1190, 1191, 1192, 1193, 1194, 1195, 1196, 1197, 1198, 1199, 1200, 1201, 1202, 1203, 1204, 1205, 1206, 1207, 1208, 1209, 1210, 1211, 1212, 1213, 1214, 1215, 1216, 1217, 1218, 1219, 1220, 1221, 1222, 1223, 1224, 1225, 1226, 1227, 1228, 1229, 1230, 1231, 1232, 1233, 1234, 1235, 1236, 1237, 1238, 1239, 1240, 1241, 1242, 1243, 1244, 1245, 1246, 1247, 1248, 1249, 1250, 1251, 1252, 1253, 1254, 1255, 1256, 1257, 1258, 1259, 1260, 1261, 1262, 1263, 1264, 1265, 1266, 1267, 1268, 1269, 1270, 1271, 1272, 1273, 1274, 1275, 1276, 1277, 1278, 1279, 1280, 1281, 1282, 1283, 1284, 1285, 1286, 1287, 1288, 1289, 1290, 1291, 1292, 1293, 1294, 1295, 1296, 1297, 1298, 1299, 1300, 1301, 1302, 1303, 1304, 1305, 1306, 1307, 1308, 1309, 1310, 1311, 1312, 1313, 1314, 1315, 1316, 1317, 1318, 1319, 1320, 1321, 1322, 1323, 1324, 1325, 1326, 1327, 1328, 1329, 1330, 1331, 1332, 1333, 1334, 1335, 1336, 1337, 1338, 1339, 1340, 1341, 1342, 1343, 1344, 1345, 1346, 1347, 1348, 1349, 1350, 1351, 1352, 1353, 1354, 1355, 1356, 1357, 1358, 1359, 1360, 1361, 1362, 1363, 1364, 1365, 1366, 1367, 1368, 1369, 1370, 1371, 1372, 1373, 1374, 1375, 1376, 1377, 1378, 1379, 1380, 1381, 1382, 1383, 1384, 1385, 1386, 1387, 1388, 1389, 1390, 1391, 1392, 1393, 1394, 1395, 1396, 1397, 1398, 1399, 1400, 1401, 1402, 1403, 1404, 1405, 1406, 1407, 1408, 1409, 1410, 1411, 1412, 1413, 1414, 1415, 1416, 1417, 1418, 1419, 1420, 1421, 1422, 1423, 1424, 1425, 1426, 1427, 1428, 1429, 1430, 1431, 1432, 1433, 1434, 1435, 1436, 1437, 1438, 1439, 1440, 1441, 1442, 1443, 1444, 1445, 1446, 1447, 1448, 1449, 1450, 1451, 1452, 1453, 1454, 1455, 1456, 1457, 1458, 1459, 1460, 1461, 1462, 1463, 1464, 1465, 1466, 1467, 1468, 1469, 1470, 1471, 1472, 1473, 1474, 1475, 1476, 1477, 1478, 1479, 1480, 1481, 1482, 1483, 1484, 1485, 1486, 1487, 1488, 1489, 1490, 1491, 1492, 1493, 1494, 1495, 1496, 1497, 1498, 1499, 1500, 1501, 1502, 1503, 1504, 1505, 1506, 1507, 1508, 1509, 1510, 1511, 1512, 1513, 1514, 1515, 1516, 1517, 1518, 1519, 1520, 1521, 1522, 1523, 1524, 1525, 1526, 1527, 1528, 1529, 1530, 1531, 1532, 1533, 1534, 1535, 1536, 1538, 1539, 1540, 1541, 1542, 1543, 1544, 1545, 1546, 1547, 1548, 1549, 1550, 1551, 1552, 1553, 1554, 1555, 1556, 1557, 1558, 1559, 1560, 1561, 1562, 1563, 1564, 1565, 1566, 1567, 1568, 1569, 1570, 1571, 1572, 1573, 1574, 1575, 1576, 1577, 1578, 1579, 1580, 1581, 1582, 1583, 1584, 1585, 1586, 1587, 1588, 1589, 1590, 1591, 1592, 1593, 1594, 1595, 1596, 1597, 1598, 1599, 1600, 1601, 1602, 1603, 1604, 1605, 1606, 1607, 1608, 1609, 1610, 1611, 1612, 1613, 1614, 1615, 1616, 1617, 1618, 1619, 1620, 1621, 1622, 1623, 1624, 1625, 1626, 1627, 1628, 1629, 1630, 1631, 1632, 1633, 1634, 1635, 1636, 1637, 1638, 1639, 1640, 1641, 1642, 1643, 1644, 1645, 1646, 1647, 1648, 1649, 1650, 1651, 1652, 1653, 1654, 1655, 1656, 1657, 1658, 1659, 1660, 1661, 1662, 1663, 1664, 1665, 1666, 1667, 1668, 1669, 1670, 1671, 1672, 1673, 1674, 1675, 1676, 1677, 1678, 1679, 1680, 1681, 1682, 1683, 1684, 1685, 1686, 1687, 1688, 1689, 1690, 1691, 1692, 1693, 1694, 1695, 1696, 1697, 1698, 1699, 1700, 1701, 1702, 1703, 1704, 1705, 1706, 1707, 1708, 1709, 1710, 1711, 1712, 1713, 1714, 1715, 1716, 1717, 1718, 1719, 1720, 1721, 1722, 1723, 1724, 1725, 1726, 1727, 1728, 1729, 1730, 1731, 1732, 1733, 1734, 1735, 1736, 1737, 1738, 1739, 1740, 1741, 1742, 1743, 1744, 1745, 1746, 1747, 1748, 1749, 1750, 1751, 1752, 1753, 1754, 1755, 1756, 1757, 1758, 1759, 1760, 1761, 1762, 1763, 1764, 1765, 1766, 1767, 1768, 1769, 1770, 1771, 1772, 1773, 1774, 1775, 1776, 1777, 1778, 1779, 1780, 1781, 1782, 1783, 1784, 1785, 1786, 1787, 1788, 1789, 1790, 1791, 1792, 1793, 1794, 1795, 1796, 1797, 1798, 1799, 1800, 1801, 1802, 1803, 1804, 1805, 1806, 1807, 1808, 1809, 1810, 1811, 1812, 1813, 1814, 1815, 1816, 1817, 1818, 1819, 1820, 1821, 1822, 1823, 1824, 1825, 1826, 1827, 1828, 1829, 1830, 1831, 1832, 1833, 1834, 1835, 1836, 1837, 1838, 1839, 1840, 1841, 1842, 1843, 1844, 1845, 1846, 1847, 1848, 1849, 1850, 1851, 1852, 1853, 1854, 1855, 1856, 1857, 1858, 1859, 1860, 1861, 1862, 1863, 1864, 1865, 1866, 1867, 1868, 1869, 1870, 1871, 1872, 1873, 1874, 1875, 1876, 1877, 1878, 1879, 1880, 1881, 1882, 1883, 1884, 1885, 1886, 1887, 1888, 1889, 1890, 1891, 1892, 1893, 1894, 1895, 1896, 1897, 1898, 1899, 1900, 1901, 1902, 1903, 1904, 1905, 1906, 1907, 1908, 1909, 1910, 1911, 1912, 1913, 1914, 1915, 1916, 1917, 1918, 1919, 1920, 1921, 1922, 1923, 1924, 1925, 1926, 1927, 1928, 1929, 1930, 1931, 1932, 1933, 1934, 1935, 1936, 1937, 1938, 1939, 1940, 1941, 1942, 1943, 1944, 1945, 1946, 1947, 1949, 1950, 1951, 1952, 1953, 1954, 1955, 1956, 1957, 1958, 1959, 1960, 1961, 1962, 1963, 1964, 1965, 1966, 1967, 1968, 1969, 1970, 1971, 1972, 1973, 1974, 1975, 1976, 1977, 1978, 1979, 1980, 1981, 1982, 1983, 1984, 1985, 1986, 1987, 1988, 1989, 1990, 1991, 1992, 1993, 1994, 1995, 1996, 1997, 1999, 2000, 2001, 2002, 2003, 2004, 2006, 2007, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024, 2025, 2026, 2027, 2028, 2029, 2030, 2031, 2032, 2033, 2034, 2035, 2036, 2037, 2038, 2039, 2040, 2041, 2042, 2043, 2044, 2046, 2047, 2048, 2049, 2050, 2051, 2052, 2053, 2054, 2056, 2057, 2058, 2059, 2060, 2061, 2062, 2063, 2064, 2065, 2066, 2067, 2068, 2069, 2070, 2071, 2072, 2073, 2074, 2075, 2076, 2077, 2078, 2079, 2080, 2081, 2082, 2083, 2084, 2085, 2086, 2087, 2088, 2089, 2090, 2091, 2092, 2093, 2094, 2095, 2096, 2097, 2098, 2099, 2100, 2101, 2102, 2103, 2104, 2105, 2106, 2107, 2108, 2109, 2110, 2111, 2112, 2113, 2114, 2115, 2116, 2117, 2118, 2119, 2120, 2121, 2122, 2123, 2124, 2125, 2126, 2127, 2128, 2129, 2130, 2131, 2132, 2133, 2134, 2135, 2136, 2137, 2138, 2139, 2140, 2141, 2142, 2143, 2144, 2145, 2146, 2147, 2148, 2149, 2150, 2151, 2152, 2153, 2154, 2155, 2156, 2157, 2158, 2159, 2160, 2161, 2162, 2163, 2164, 2165, 2166, 2167, 2168, 2169, 2170, 2171, 2172, 2173, 2174, 2175, 2176, 2177, 2178, 2179, 2180, 2181, 2182, 2183, 2184, 2185, 2186, 2187, 2188, 2189, 2190, 2191, 2192, 2193, 2194, 2195, 2196, 2197, 2198, 2199, 2200, 2201, 2202, 2203, 2204, 2205, 2206, 2207, 2208, 2209, 2210, 2211, 2212, 2213, 2214, 2215, 2216, 2217, 2218, 2219, 2220, 2221, 2222, 2223, 2224, 2225, 2226, 2227, 2228, 2229, 2230, 2231, 2232, 2233, 2234, 2235, 2236, 2237, 2238, 2239, 2240, 2241, 2242, 2243, 2244, 2245, 2246, 2247, 2248, 2249, 2250, 2251, 2252, 2253, 2254, 2255, 2256, 2257, 2258, 2259, 2260, 2261, 2262, 2263, 2264, 2265, 2266, 2267, 2268, 2269, 2270, 2271, 2272, 2273, 2274, 2275, 2276, 2277, 2278, 2279, 2280, 2281, 2282, 2283, 2284, 2285, 2286, 2287, 2288, 2289, 2290, 2291, 2292, 2293, 2294, 2295, 2296, 2297, 2298, 2299, 2300, 2301, 2302, 2303, 2304, 2305, 2306, 2307, 2308, 2309, 2310, 2311, 2312, 2313, 2314, 2315, 2316, 2317, 2318, 2319, 2320, 2321, 2322, 2323, 2324, 2325, 2326, 2327, 2328, 2329, 2330, 2331, 2332, 2333, 2334, 2335, 2336, 2337, 2338, 2339, 2340, 2341, 2342, 2343, 2344, 2345, 2346, 2347, 2348, 2349, 2350, 2351, 2352, 2353, 2354, 2355, 2356, 2357, 2358, 2359, 2360, 2361, 2362, 2363, 2364, 2365, 2366, 2367, 2368, 2369, 2370, 2371, 2372, 2373, 2375, 2376, 2377, 2378, 2379, 2380, 2381, 2382, 2383, 2384, 2386, 2387, 2388, 2389, 2390, 2391, 2392, 2393, 2394, 2395, 2396, 2397, 2398, 2399, 2400, 2401, 2402, 2403, 2404, 2405, 2406, 2407, 2408, 2409, 2410, 2411, 2412, 2413, 2414, 2415, 2416, 2417, 2418, 2419, 2420, 2421, 2424, 2425, 2426, 2427, 2430, 2431, 2432, 2433, 2434, 2435, 2436, 2437, 2438, 2439, 2440, 2441, 2442, 2443, 2444, 2445, 2446, 2447, 2448, 2449, 2450, 2451, 2452, 2453, 2454, 2455, 2456, 2457, 2458, 2459, 2460, 2461, 2462, 2463, 2464, 2465, 2466, 2467, 2468, 2469, 2470, 2471, 2472, 2473, 2474, 2475, 2476, 2477, 2478, 2479, 2480, 2481, 2482, 2483, 2484, 2485, 2486, 2487, 2488, 2489, 2490, 2491, 2492, 2493, 2494, 2495, 2496, 2497, 2498, 2499, 2500, 2501, 2502, 2503, 2504, 2505, 2506, 2507, 2508, 2509, 2510, 2511, 2512, 2513, 2514, 2515, 2516, 2517, 2518, 2519, 2520, 2521, 2522, 2523, 2524, 2525, 2526, 2527, 2528, 2529, 2530, 2531, 2532, 2533, 2534, 2535, 2536, 2537, 2538, 2539, 2540, 2541, 2542, 2543, 2544, 2545, 2546, 2547, 2548, 2549, 2550, 2551, 2552, 2553, 2554, 2555, 2556, 2557, 2558, 2559, 2560, 2561, 2562, 2563, 2564, 2565, 2566, 2567, 2568, 2569, 2570, 2571, 2572, 2573, 2574, 2575, 2576, 2577, 2578, 2579, 2580, 2581, 2582, 2583, 2584, 2585, 2586, 2587, 2588, 2589, 2590, 2591, 2592, 2593, 2594, 2595, 2596, 2597, 2598, 2599, 2600, 2601, 2602, 2603, 2604, 2605, 2606, 2607, 2608, 2609, 2610, 2611, 2612, 2613, 2614, 2615, 2616, 2617, 2618, 2619, 2620, 2621, 2622, 2623, 2624, 2625, 2626, 2627, 2628, 2629, 2630, 2631, 2632, 2633, 2634, 2635, 2636, 2637, 2638, 2639, 2640, 2641, 2642, 2643, 2644, 2645, 2646, 2647, 2648, 2649, 2650, 2651, 2652, 2653, 2654, 2655, 2656, 2657, 2658, 2659, 2660, 2661, 2662, 2663, 2664, 2665, 2666, 2667, 2668, 2669, 2670, 2671, 2672, 2673, 2674, 2675, 2676, 2677, 2678, 2679, 2680, 2681, 2682, 2683, 2684, 2685, 2686, 2687, 2688, 2689, 2690, 2691, 2692, 2693, 2694, 2695, 2696, 2697, 2698, 2699, 2700, 2701, 2702, 2703, 2704, 2705, 2706, 2707, 2708, 2709, 2710, 2711, 2712, 2713, 2714, 2715, 2716, 2717, 2718, 2719, 2720, 2721, 2722, 2723, 2724, 2725, 2726, 2727, 2728, 2729, 2730, 2731, 2732, 2733, 2734, 2735, 2736, 2737, 2738, 2739, 2740, 2741, 2742, 2743, 2744, 2745, 2746, 2747, 2748, 2749, 2750, 2751, 2752, 2753, 2754, 2755, 2756, 2757, 2758, 2759, 2760, 2761, 2762, 2763, 2764, 2765, 2766, 2767, 2768, 2769, 2770, 2771, 2772, 2773, 2774, 2775, 2776, 2777, 2778, 2779, 2780, 2781, 2782, 2783, 2784, 2785, 2786, 2787, 2788, 2789, 2790, 2791, 2792, 2793, 2794, 2795, 2796, 2797, 2798, 2799, 2800, 2801, 2802, 2803, 2804, 2805, 2806, 2807, 2808, 2809, 2810, 2811, 2812, 2813, 2814, 2815, 2816, 2817, 2818, 2819, 2820, 2821, 2822, 2823, 2824, 2825, 2826, 2827, 2828, 2829, 2830, 2831, 2832, 2833, 2834, 2835, 2836, 2837, 2838, 2839, 2840, 2841, 2842, 2843, 2844, 2845, 2846, 2847, 2848, 2849, 2850, 2851, 2852, 2853, 2854, 2855, 2856, 2857, 2858, 2859, 2860, 2861, 2862, 2863, 2864, 2865, 2866, 2867, 2868, 2869, 2870, 2871, 2872, 2873, 2874, 2875, 2876, 2877, 2878, 2879, 2880, 2881, 2882, 2883, 2884, 2885, 2886, 2887, 2888, 2889, 2890, 2891, 2892, 2893, 2894, 2895, 2896, 2897, 2898, 2899, 2900, 2901, 2903, 2904, 2905, 2906, 2907, 2908, 2910, 2911, 2912, 2913, 2914, 2915, 2917, 2918, 2919, 2920, 2921, 2922, 2924, 2925, 2927, 2928, 2932, 2934, 2935, 2936, 2939, 2940, 2941, 2944, 2946, 2948, 2949, 2950, 2951, 2952, 2953, 2954, 2955, 2956, 2957, 2959, 2960, 2961, 2962, 2963, 2964, 2965, 2966, 2967, 2968, 2969, 2970, 2971, 2972, 2973, 2974, 2977, 2978, 2979, 2980, 2981, 2982, 2983, 2985, 2986, 2987, 2988, 2989, 2990, 2991, 2992, 2993, 2995, 2996, 2997, 2998, 2999, 3000, 3001, 3002, 3003, 3004, 3005, 3006, 3007, 3008, 3009, 3010, 3013, 3015, 3016, 3019, 3020, 3021, 3022, 3024, 3025, 3026, 3027, 3028, 3029, 3030, 3031, 3032, 3033, 3034, 3035, 3036, 3037, 3038, 3039, 3040, 3041, 3042, 3043, 3044, 3045, 3046, 3047, 3048, 3049, 3050, 3051, 3052, 3053, 3054, 3055, 3056, 3057, 3058, 3059, 3060, 3061, 3062, 3063, 3064, 3065, 3066, 3067, 3068, 3069, 3070, 3071, 3072, 3073, 3074, 3075, 3076, 3077, 3078, 3079, 3080, 3081, 3082, 3083, 3084, 3085, 3086, 3087, 3088, 3089, 3090, 3091, 3092, 3093, 3094, 3095, 3096, 3097, 3098, 3099, 3100, 3101, 3102, 3103, 3104, 3105, 3106, 3107, 3108, 3109, 3110, 3111, 3112, 3113, 3114, 3115, 3116, 3117, 3118, 3119, 3120, 3121, 3122, 3123, 3124, 3125, 3126, 3127, 3128, 3129, 3130, 3131, 3132, 3133, 3134, 3135, 3136, 3137, 3138, 3139, 3140, 3141, 3142, 3143, 3144, 3145, 3146, 3147, 3148, 3149, 3150, 3151, 3152, 3153, 3154, 3155, 3156, 3157, 3158, 3159, 3160, 3161, 3162, 3163, 3164, 3165, 3166, 3167, 3168, 3169, 3170, 3171, 3172, 3173, 3174, 3175, 3176, 3177, 3178, 3179, 3180, 3181, 3182, 3183, 3184, 3185, 3186, 3187, 3188, 3189, 3190, 3191, 3192, 3193, 3194, 3195, 3196, 3197, 3198, 3199, 3200, 3201, 3202, 3203, 3204, 3205, 3206, 3207, 3208, 3209, 3210, 3211, 3212, 3213, 3214, 3215, 3216, 3217, 3218, 3219, 3220, 3221, 3222, 3223, 3224, 3225, 3226, 3227, 3228, 3229, 3230, 3231, 3232, 3233, 3234, 3235, 3236, 3237, 3238, 3239, 3240, 3241, 3242, 3243, 3244, 3245, 3246, 3247, 3248, 3249, 3250, 3251, 3252, 3253, 3254, 3255, 3256, 3257, 3258, 3259, 3260, 3261, 3262, 3263, 3264, 3265, 3266, 3267, 3268, 3269, 3270, 3271, 3272, 3273, 3274, 3275, 3276, 3277, 3278, 3279, 3280, 3281, 3282, 3283, 3284, 3285, 3286, 3287, 3288, 3289, 3290, 3291, 3292, 3293, 3294, 3295, 3296, 3297, 3298, 3299, 3300, 3301, 3302, 3303, 3304, 3305, 3306, 3307, 3308, 3309, 3310, 3311, 3312, 3313, 3314, 3315, 3316, 3317, 3318, 3319, 3320, 3321, 3322, 3323, 3324, 3325, 3326, 3327, 3328, 3329, 3330, 3331, 3332, 3333, 3334, 3335, 3336, 3337, 3338, 3339, 3340, 3341, 3342, 3343, 3344, 3345, 3346, 3347, 3348, 3349, 3350, 3351, 3352, 3353, 3354, 3355, 3356, 3357, 3358, 3359, 3360, 3361, 3362, 3363, 3364, 3365, 3366, 3367, 3368, 3369, 3370, 3371, 3372, 3373, 3374, 3375, 3376, 3377, 3378, 3379, 3380, 3381, 3382, 3383, 3384, 3385, 3386, 3387, 3388, 3389, 3390, 3391, 3392, 3393, 3394, 3395, 3396, 3397, 3398, 3399, 3400, 3401, 3402, 3403, 3404, 3405, 3406, 3407, 3408, 3409, 3410, 3411, 3412, 3413, 3414, 3415, 3416, 3417, 3418, 3419, 3420, 3421, 3422, 3423, 3424, 3425, 3426, 3427, 3428, 3429, 3430, 3431, 3432, 3433, 3434, 3435, 3436, 3437, 3438, 3439, 3440, 3441, 3442, 3443, 3444, 3445, 3446, 3447, 3448, 3449, 3450, 3451, 3452, 3453, 3454, 3455, 3456, 3457, 3458, 3459, 3460, 3461, 3462, 3463, 3464, 3465, 3466, 3467, 3468, 3469, 3470, 3471, 3472, 3473, 3474, 3475, 3476, 3477, 3478, 3479, 3480, 3481, 3482, 3483, 3484, 3485, 3486, 3487, 3488, 3489, 3490, 3491, 3492, 3493, 3494, 3495, 3496, 3497, 3498, 3499, 3500, 3501, 3502, 3503, 3504, 3505, 3506, 3507, 3508, 3509, 3510, 3511, 3512, 3513, 3514, 3515, 3516, 3517, 3518, 3519, 3520, 3521, 3522, 3523, 3524, 3525, 3526, 3527, 3528, 3529, 3530, 3531, 3532, 3533, 3534, 3535, 3536, 3537, 3538, 3539, 3540, 3541, 3542, 3543, 3544, 3545, 3546, 3547, 3548, 3549, 3550, 3551, 3552, 3553, 355

In [36]:
print(len(G.nodes))
print(len(G.edges))

3768
57994

In [26]:
from networkx.algorithms.community.quality import modularity
partition = community_louvain.best_partition(G,resolution=0.9, weight='weight')
#partition = community_louvain.best_partition(G, resolution=0.9)
kume_sayisi = max(partition.values()) + 1
modularity = community_louvain.modularity(partition, G, weight='weight')
print(f"\nOptimal Küme Sayısı: {kume_sayisi}")
print(f"Modularity Değeri: {modularity:.4f}")

Optimal Küme Sayısı: 24
Modularity Değeri: 0.6189

In [40]:
unique_communities = set(partition.values())
#print("Benzersiz Topluluklar:", unique_communities) 
# Toplulukları düğümlere göre grupla
community_to_nodes = defaultdict(list)

for node, community in partition.items():
    community_to_nodes[community].append(node)

# Her topluluğu ve düğümlerini yazdır
for comm, nodes in community_to_nodes.items():
    print(f"Topluluk {comm}: {nodes}")

Topluluk 0: [0, 12, 25, 40, 46, 78, 96, 97, 129, 133, 134, 137, 150, 156, 163, 175, 184, 201, 210, 227, 250, 271, 274, 286, 301, 309, 327, 335, 344, 345, 348, 354, 356, 364, 378, 387, 422, 426, 441, 455, 461, 481, 484, 494, 520, 550, 554, 564, 590, 611, 628, 635, 637, 639, 640, 653, 659, 669, 673, 676, 678, 681, 689, 691, 692, 743, 744, 746, 748, 754, 770, 779, 801, 816, 819, 826, 855, 856, 871, 873, 886, 899, 904, 917, 928, 937, 938, 962, 964, 966, 983, 989, 1002, 1003, 1009, 1024, 1037, 1038, 1041, 1051, 1068, 1078, 1080, 1086, 1089, 1109, 1119, 1121, 1130, 1139, 1147, 1199, 1207, 1210, 1212, 1228, 1237, 1259, 1278, 1307, 1315, 1339, 1346, 1350, 1351, 1352, 1360, 1379, 1395, 1397, 1402, 1425, 1437, 1446, 1452, 1454, 1455, 1461, 1463, 1464, 1480, 1488, 1493, 1508, 1510, 1511, 1515, 1524, 1526, 1528, 1562, 1573, 1584, 1587, 1598, 1601, 1603, 1612, 1616, 1623, 1635, 1638, 1649, 1650, 1664, 1668, 1680, 1683, 1685, 1690, 1707, 1743, 1753, 1759, 1776, 1785, 1788, 1791, 1794, 1796, 1801, 1804, 1814, 1830, 1834, 1878, 1888, 1890, 1913, 1922, 1943, 1946, 1947, 1955, 1957, 1958, 1968, 1975, 2017, 2031, 2034, 2038, 2050, 2071, 2072, 2073, 2074, 2078, 2080, 2088, 2090, 2093, 2097, 2108, 2120, 2121, 2125, 2138, 2142, 2158, 2159, 2170, 2174, 2192, 2193, 2200, 2205, 2210, 2227, 2237, 2247, 2273, 2308, 2311, 2325, 2326, 2341, 2345, 2360, 2361, 2363, 2370, 2373, 2381, 2411, 2442, 2443, 2445, 2447, 2449, 2480, 2481, 2491, 2497, 2507, 2519, 2540, 2555, 2565, 2567, 2588, 2593, 2600, 2606, 2632, 2645, 2653, 2654, 2661, 2663, 2665, 2667, 2698, 2721, 2730, 2732, 2737, 2756, 2762, 2775, 2794, 2795, 2796, 2797, 2806, 2839, 2844, 2853, 2864, 2871, 2872, 2904, 2914, 2915, 2934, 2961, 2963, 2965, 2974, 2993, 3032, 3039, 3055, 3056, 3060, 3073, 3085, 3089, 3091, 3115, 3126, 3130, 3147, 3155, 3163, 3164, 3168, 3173, 3174, 3180, 3186, 3200, 3212, 3227, 3232, 3239, 3248, 3252, 3275, 3283, 3287, 3316, 3320, 3329, 3362, 3364, 3367, 3373, 3378, 3384, 3388, 3412, 3424, 3439, 3448, 3492, 3494, 3496, 3518, 3520, 3524, 3534, 3554, 3561, 3563, 3575, 3590, 3595, 3618, 3623, 3625, 3627, 3628, 3633, 3645, 3670, 3679, 3693, 3699, 3701, 3706, 3717, 3726, 3748, 3782, 3787]
Topluluk 11: [1, 2, 8, 18, 20, 26, 27, 35, 36, 37, 45, 59, 65, 89, 94, 99, 103, 112, 135, 144, 158, 166, 187, 198, 206, 207, 211, 214, 219, 239, 241, 258, 261, 264, 265, 268, 273, 282, 284, 287, 302, 306, 319, 323, 326, 328, 329, 341, 347, 350, 353, 360, 367, 368, 371, 382, 388, 389, 394, 395, 398, 399, 401, 402, 417, 420, 421, 432, 436, 443, 451, 465, 467, 475, 479, 491, 495, 501, 517, 518, 521, 524, 525, 527, 528, 543, 545, 553, 555, 556, 558, 563, 567, 586, 592, 597, 599, 613, 614, 617, 620, 629, 631, 632, 648, 655, 656, 657, 663, 671, 675, 686, 687, 710, 711, 715, 729, 731, 740, 745, 762, 765, 783, 794, 795, 802, 813, 828, 836, 839, 846, 851, 858, 860, 866, 868, 878, 882, 887, 892, 900, 902, 921, 923, 935, 940, 953, 958, 963, 986, 991, 1000, 1001, 1006, 1015, 1018, 1020, 1029, 1033, 1034, 1065, 1070, 1075, 1077, 1081, 1083, 1087, 1088, 1104, 1114, 1115, 1118, 1136, 1140, 1148, 1150, 1151, 1152, 1155, 1175, 1181, 1194, 1205, 1216, 1218, 1221, 1232, 1245, 1247, 1249, 1251, 1255, 1258, 1265, 1284, 1285, 1287, 1295, 1300, 1309, 1310, 1312, 1326, 1327, 1342, 1344, 1358, 1361, 1365, 1376, 1382, 1385, 1388, 1394, 1396, 1401, 1411, 1412, 1428, 1430, 1435, 1441, 1443, 1469, 1471, 1475, 1477, 1487, 1492, 1497, 1499, 1500, 1502, 1519, 1532, 1533, 1541, 1549, 1554, 1567, 1571, 1576, 1580, 1582, 1583, 1592, 1611, 1621, 1637, 1641, 1642, 1652, 1656, 1663, 1665, 1667, 1678, 1682, 1684, 1701, 1716, 1729, 1735, 1744, 1748, 1750, 1755, 1756, 1766, 1772, 1775, 1777, 1786, 1792, 1798, 1808, 1812, 1822, 1825, 1826, 1831, 1837, 1838, 1854, 1861, 1865, 1870, 1871, 1872, 1884, 1893, 1909, 1938, 1940, 1945, 1950, 1952, 1960, 1966, 1969, 1971, 1973, 1978, 1979, 1983, 1987, 2000, 2002, 2004, 2026, 2029, 2035, 2040, 2051, 2057, 2067, 2068, 2069, 2082, 2095, 2099, 2100, 2103, 2104, 2109, 2111, 2118, 2119, 2122, 2136, 2137, 2141, 2150, 2153, 2155, 2161, 2163, 2166, 2167, 2176, 2180, 2182, 2188, 2195, 2196, 2208, 2215, 2220, 2221, 2224, 2228, 2230, 2232, 2235, 2246, 2251, 2257, 2260, 2261, 2265, 2267, 2268, 2270, 2277, 2278, 2298, 2301, 2313, 2323, 2337, 2342, 2357, 2358, 2369, 2371, 2377, 2379, 2392, 2402, 2407, 2421, 2430, 2439, 2441, 2448, 2475, 2496, 2498, 2505, 2508, 2515, 2526, 2534, 2541, 2542, 2544, 2558, 2568, 2573, 2578, 2582, 2585, 2596, 2601, 2604, 2609, 2613, 2616, 2618, 2638, 2640, 2641, 2649, 2650, 2664, 2668, 2671, 2673, 2677, 2685, 2695, 2699, 2713, 2717, 2755, 2768, 2773, 2774, 2781, 2784, 2803, 2813, 2815, 2820, 2821, 2837, 2845, 2852, 2860, 2867, 2893, 2897, 2906, 2922, 2941, 2948, 2949, 2959, 2962, 2971, 2979, 3001, 3006, 3008, 3013, 3016, 3019, 3030, 3038, 3046, 3050, 3051, 3072, 3075, 3086, 3087, 3092, 3097, 3105, 3109, 3112, 3116, 3131, 3144, 3153, 3154, 3161, 3169, 3179, 3182, 3187, 3192, 3195, 3207, 3210, 3216, 3219, 3220, 3230, 3231, 3234, 3244, 3257, 3266, 3268, 3277, 3290, 3291, 3313, 3327, 3332, 3336, 3343, 3345, 3359, 3360, 3369, 3372, 3394, 3404, 3409, 3422, 3425, 3437, 3441, 3444, 3450, 3455, 3465, 3466, 3469, 3473, 3479, 3480, 3482, 3488, 3489, 3490, 3506, 3513, 3516, 3517, 3521, 3527, 3528, 3532, 3537, 3541, 3564, 3566, 3584, 3585, 3593, 3597, 3599, 3603, 3609, 3617, 3619, 3626, 3647, 3655, 3661, 3673, 3676, 3677, 3688, 3698, 3702, 3711, 3720, 3746, 3764, 3776, 3786, 3789, 3792, 3801, 3802, 3803, 3804, 3805]
Topluluk 2: [3, 4, 6, 7, 15, 16, 21, 31, 41, 51, 56, 61, 64, 67, 68, 69, 74, 81, 92, 93, 106, 113, 125, 130, 141, 147, 148, 149, 151, 159, 160, 171, 179, 181, 189, 191, 192, 193, 194, 204, 213, 217, 224, 225, 230, 235, 236, 237, 240, 242, 254, 256, 259, 272, 276, 293, 294, 310, 317, 318, 321, 325, 337, 362, 366, 372, 374, 380, 381, 390, 405, 409, 410, 414, 416, 418, 428, 430, 434, 435, 449, 462, 466, 472, 473, 498, 504, 506, 507, 510, 529, 537, 538, 546, 562, 568, 572, 579, 580, 582, 591, 607, 609, 616, 624, 636, 651, 652, 658, 660, 661, 664, 667, 674, 680, 684, 685, 697, 712, 716, 719, 722, 723, 727, 736, 741, 742, 756, 768, 772, 773, 775, 777, 778, 784, 790, 796, 800, 807, 814, 815, 835, 845, 854, 864, 867, 876, 877, 880, 889, 896, 897, 901, 918, 931, 933, 936, 939, 944, 947, 948, 957, 967, 969, 974, 979, 1007, 1026, 1072, 1084, 1092, 1093, 1095, 1098, 1102, 1117, 1127, 1133, 1153, 1169, 1171, 1176, 1177, 1190, 1191, 1204, 1206, 1213, 1215, 1272, 1276, 1282, 1286, 1292, 1302, 1313, 1314, 1334, 1336, 1337, 1338, 1356, 1357, 1370, 1372, 1373, 1386, 1387, 1391, 1393, 1398, 1405, 1415, 1419, 1421, 1423, 1427, 1439, 1457, 1467, 1472, 1479, 1483, 1491, 1498, 1509, 1514, 1516, 1520, 1527, 1535, 1542, 1546, 1551, 1556, 1557, 1570, 1578, 1579, 1586, 1588, 1593, 1604, 1634, 1648, 1653, 1671, 1673, 1687, 1688, 1692, 1697, 1703, 1711, 1720, 1723, 1737, 1767, 1769, 1780, 1782, 1807, 1816, 1817, 1818, 1836, 1842, 1843, 1847, 1850, 1856, 1859, 1860, 1866, 1879, 1885, 1896, 1902, 1914, 1939, 1942, 1944, 1949, 1962, 1963, 1965, 1970, 1974, 1988, 1989, 2018, 2028, 2033, 2043, 2044, 2052, 2058, 2059, 2062, 2066, 2075, 2081, 2084, 2092, 2105, 2116, 2127, 2128, 2135, 2139, 2140, 2144, 2146, 2160, 2165, 2173, 2185, 2186, 2190, 2206, 2213, 2219, 2222, 2223, 2225, 2226, 2242, 2248, 2254, 2255, 2266, 2280, 2285, 2286, 2287, 2324, 2333, 2335, 2340, 2343, 2344, 2349, 2352, 2365, 2366, 2376, 2380, 2382, 2384, 2387, 2389, 2393, 2394, 2396, 2400, 2401, 2417, 2427, 2431, 2436, 2451, 2459, 2460, 2474, 2477, 2487, 2495, 2499, 2506, 2514, 2530, 2532, 2535, 2549, 2553, 2554, 2569, 2575, 2587, 2591, 2594, 2605, 2611, 2630, 2635, 2642, 2656, 2660, 2674, 2676, 2688, 2696, 2715, 2731, 2733, 2747, 2748, 2749, 2750, 2761, 2765, 2767, 2778, 2788, 2789, 2816, 2818, 2832, 2840, 2841, 2842, 2847, 2850, 2855, 2861, 2862, 2873, 2888, 2913, 2918, 2951, 2953, 2960, 2977, 2988, 2990, 2992, 2998, 2999, 3003, 3020, 3025, 3026, 3035, 3037, 3047, 3053, 3058, 3062, 3066, 3068, 3070, 3079, 3080, 3100, 3104, 3111, 3113, 3134, 3139, 3145, 3159, 3184, 3188, 3189, 3191, 3194, 3201, 3215, 3217, 3224, 3245, 3247, 3253, 3254, 3256, 3259, 3265, 3272, 3279, 3293, 3295, 3297, 3298, 3302, 3304, 3308, 3325, 3326, 3333, 3357, 3358, 3366, 3381, 3382, 3385, 3386, 3387, 3398, 3401, 3408, 3410, 3411, 3414, 3418, 3431, 3433, 3436, 3449, 3451, 3454, 3462, 3485, 3486, 3491, 3493, 3498, 3500, 3507, 3529, 3555, 3567, 3573, 3574, 3576, 3577, 3587, 3589, 3592, 3608, 3611, 3622, 3629, 3632, 3637, 3638, 3644, 3646, 3654, 3658, 3662, 3663, 3664, 3666, 3672, 3675, 3691, 3696, 3697, 3700, 3705, 3710, 3712, 3728, 3733, 3737, 3745, 3749, 3753, 3759, 3765, 3770, 3771, 3778, 3793]
Topluluk 3: [5, 11, 13, 17, 22, 24, 34, 42, 48, 50, 52, 57, 58, 75, 77, 79, 95, 98, 104, 105, 107, 111, 121, 122, 124, 126, 139, 153, 154, 157, 164, 168, 172, 174, 177, 178, 195, 196, 215, 220, 221, 229, 231, 243, 252, 257, 263, 266, 292, 297, 298, 307, 336, 339, 351, 355, 363, 383, 393, 397, 400, 407, 419, 437, 454, 474, 485, 490, 492, 505, 533, 540, 542, 544, 549, 601, 604, 615, 623, 645, 682, 707, 709, 713, 732, 734, 752, 763, 771, 780, 787, 791, 792, 798, 810, 833, 840, 849, 859, 863, 898, 903, 909, 910, 922, 926, 950, 965, 968, 972, 993, 995, 996, 1016, 1036, 1047, 1050, 1054, 1057, 1062, 1063, 1066, 1094, 1101, 1137, 1141, 1142, 1143, 1144, 1180, 1203, 1225, 1230, 1236, 1238, 1241, 1252, 1266, 1267, 1268, 1291, 1294, 1298, 1323, 1329, 1330, 1366, 1368, 1381, 1383, 1389, 1414, 1418, 1429, 1433, 1438, 1440, 1448, 1473, 1525, 1559, 1560, 1563, 1568, 1613, 1618, 1646, 1651, 1674, 1677, 1695, 1702, 1706, 1727, 1740, 1741, 1768, 1771, 1797, 1806, 1820, 1840, 1852, 1862, 1886, 1903, 1918, 1919, 1923, 1924, 1967, 1981, 1993, 2039, 2048, 2094, 2098, 2110, 2112, 2113, 2114, 2124, 2126, 2131, 2157, 2162, 2172, 2177, 2245, 2252, 2256, 2259, 2272, 2292, 2314, 2386, 2399, 2406, 2413, 2416, 2433, 2484, 2486, 2492, 2576, 2595, 2598, 2603, 2617, 2637, 2655, 2662, 2669, 2672, 2679, 2686, 2700, 2708, 2718, 2727, 2728, 2736, 2741, 2742, 2764, 2766, 2769, 2777, 2787, 2807, 2809, 2811, 2827, 2831, 2834, 2863, 2879, 2881, 2905, 2966, 3000, 3004, 3114, 3129, 3160, 3190, 3214, 3228, 3286, 3292, 3344, 3348, 3393, 3397, 3399, 3417, 3429, 3435, 3484, 3504, 3538, 3581, 3582, 3586, 3598, 3602, 3612, 3624, 3631, 3634, 3651, 3669, 3683, 3694, 3707, 3709, 3713, 3731, 3757, 3761, 3768, 3777, 3790, 3800]
Topluluk 4: [9, 10, 19, 32, 33, 43, 44, 47, 49, 55, 66, 70, 71, 73, 80, 83, 108, 110, 115, 117, 118, 120, 128, 131, 140, 142, 143, 162, 167, 169, 182, 183, 185, 186, 202, 208, 209, 218, 222, 232, 244, 251, 262, 267, 270, 281, 288, 290, 296, 299, 300, 304, 308, 311, 312, 331, 332, 334, 340, 352, 358, 369, 377, 379, 385, 386, 408, 425, 427, 440, 442, 444, 448, 452, 456, 458, 464, 470, 477, 482, 486, 487, 488, 489, 496, 503, 511, 513, 514, 522, 531, 535, 536, 539, 548, 557, 559, 573, 584, 585, 588, 600, 605, 618, 619, 634, 644, 662, 668, 670, 688, 694, 695, 696, 701, 702, 703, 718, 720, 724, 737, 747, 758, 769, 781, 782, 785, 786, 788, 799, 803, 818, 820, 821, 825, 830, 843, 848, 857, 861, 862, 869, 870, 874, 884, 890, 905, 919, 927, 929, 930, 945, 952, 961, 970, 976, 981, 984, 988, 997, 1004, 1005, 1008, 1014, 1017, 1019, 1021, 1025, 1027, 1046, 1060, 1067, 1073, 1091, 1097, 1113, 1129, 1134, 1145, 1158, 1159, 1162, 1164, 1165, 1168, 1178, 1182, 1184, 1187, 1188, 1192, 1195, 1196, 1211, 1235, 1246, 1250, 1257, 1264, 1274, 1283, 1288, 1289, 1299, 1303, 1304, 1311, 1319, 1324, 1328, 1335, 1345, 1359, 1371, 1374, 1384, 1392, 1399, 1407, 1413, 1416, 1432, 1450, 1453, 1456, 1458, 1459, 1460, 1476, 1485, 1486, 1495, 1507, 1513, 1517, 1529, 1530, 1536, 1539, 1545, 1566, 1574, 1581, 1590, 1596, 1597, 1602, 1609, 1619, 1622, 1624, 1626, 1629, 1632, 1633, 1636, 1655, 1659, 1660, 1661, 1662, 1670, 1681, 1691, 1696, 1698, 1699, 1700, 1709, 1712, 1713, 1715, 1717, 1721, 1724, 1732, 1757, 1760, 1765, 1773, 1783, 1787, 1790, 1793, 1805, 1809, 1815, 1821, 1824, 1845, 1849, 1851, 1855, 1857, 1858, 1869, 1874, 1877, 1882, 1889, 1894, 1895, 1897, 1899, 1900, 1908, 1910, 1911, 1915, 1917, 1926, 1927, 1928, 1930, 1934, 1935, 1953, 1956, 1976, 1982, 1985, 1990, 1991, 1997, 2007, 2010, 2011, 2022, 2032, 2042, 2049, 2053, 2061, 2076, 2077, 2079, 2085, 2089, 2091, 2102, 2115, 2145, 2169, 2171, 2179, 2189, 2197, 2202, 2211, 2217, 2233, 2238, 2240, 2243, 2244, 2253, 2258, 2262, 2271, 2279, 2297, 2305, 2307, 2309, 2320, 2330, 2338, 2339, 2346, 2350, 2351, 2438, 2450, 2453, 2454, 2458, 2466, 2467, 2470, 2473, 2479, 2482, 2490, 2503, 2509, 2512, 2516, 2517, 2550, 2552, 2557, 2570, 2571, 2581, 2597, 2615, 2628, 2639, 2643, 2646, 2648, 2651, 2652, 2657, 2659, 2666, 2680, 2691, 2692, 2709, 2710, 2723, 2729, 2738, 2744, 2752, 2760, 2763, 2770, 2771, 2780, 2782, 2785, 2799, 2814, 2824, 2826, 2829, 2835, 2836, 2857, 2866, 2868, 2880, 2884, 2885, 2887, 2890, 2891, 2895, 2896, 2901, 2924, 2927, 2946, 2995, 2997, 3002, 3015, 3022, 3028, 3042, 3045, 3049, 3069, 3077, 3078, 3095, 3096, 3098, 3099, 3102, 3110, 3121, 3124, 3140, 3143, 3146, 3178, 3181, 3183, 3202, 3203, 3205, 3206, 3208, 3213, 3222, 3223, 3237, 3240, 3242, 3243, 3246, 3250, 3251, 3264, 3269, 3278, 3282, 3296, 3299, 3307, 3312, 3319, 3331, 3340, 3341, 3350, 3356, 3365, 3368, 3375, 3376, 3380, 3390, 3400, 3402, 3403, 3421, 3442, 3461, 3463, 3470, 3475, 3476, 3477, 3481, 3487, 3502, 3503, 3508, 3512, 3514, 3526, 3533, 3539, 3543, 3546, 3552, 3558, 3562, 3568, 3571, 3578, 3580, 3588, 3601, 3610, 3616, 3621, 3630, 3636, 3643, 3652, 3660, 3665, 3671, 3674, 3680, 3681, 3682, 3695, 3714, 3718, 3719, 3721, 3730, 3734, 3736, 3738, 3740, 3744, 3769, 3772, 3780, 3785, 3795]
Topluluk 5: [14, 29, 60, 62, 63, 76, 84, 85, 86, 87, 88, 101, 102, 114, 116, 119, 127, 152, 155, 203, 255, 275, 314, 324, 361, 370, 373, 375, 392, 411, 429, 497, 519, 532, 560, 566, 569, 577, 583, 593, 606, 646, 650, 683, 700, 704, 728, 733, 739, 753, 755, 789, 804, 811, 823, 829, 847, 852, 881, 883, 893, 908, 912, 925, 941, 942, 949, 955, 971, 982, 990, 992, 1032, 1039, 1040, 1044, 1049, 1052, 1058, 1074, 1090, 1110, 1111, 1122, 1131, 1138, 1157, 1163, 1174, 1179, 1186, 1197, 1219, 1239, 1254, 1256, 1275, 1279, 1301, 1316, 1317, 1320, 1340, 1403, 1442, 1465, 1470, 1474, 1482, 1501, 1504, 1505, 1512, 1522, 1523, 1553, 1558, 1577, 1595, 1614, 1631, 1722, 1730, 1751, 1761, 1764, 1778, 1779, 1802, 1813, 1829, 1833, 1841, 1848, 1868, 1880, 1881, 1892, 1907, 1925, 1933, 1986, 1995, 2014, 2015, 2025, 2070, 2083, 2101, 2106, 2133, 2134, 2152, 2154, 2164, 2168, 2207, 2274, 2275, 2288, 2290, 2299, 2300, 2319, 2321, 2322, 2332, 2362, 2368, 2375, 2398, 2403, 2415, 2425, 2434, 2440, 2452, 2455, 2457, 2461, 2476, 2485, 2494, 2504, 2524, 2528, 2539, 2548, 2551, 2572, 2592, 2619, 2644, 2658, 2670, 2703, 2704, 2705, 2722, 2725, 2735, 2740, 2759, 2783, 2793, 2800, 2805, 2838, 2849, 2899, 2912, 2925, 2928, 2944, 2954, 2955, 2957, 2972, 2978, 2983, 3044, 3048, 3071, 3074, 3081, 3088, 3090, 3101, 3108, 3119, 3170, 3172, 3175, 3177, 3193, 3199, 3211, 3221, 3229, 3263, 3284, 3285, 3289, 3337, 3342, 3371, 3443, 3452, 3464, 3472, 3474, 3505, 3556, 3591, 3613, 3615, 3639, 3667, 3722, 3750, 3760, 3779, 3781]
Topluluk 6: [23, 30, 38, 39, 53, 54, 100, 138, 145, 146, 180, 190, 200, 223, 245, 248, 249, 277, 291, 320, 359, 478, 480, 483, 512, 571, 595, 596, 621, 622, 641, 666, 672, 726, 750, 767, 797, 812, 817, 827, 832, 834, 888, 916, 951, 1010, 1023, 1103, 1132, 1208, 1217, 1248, 1270, 1308, 1325, 1375, 1422, 1462, 1489, 1534, 1564, 1606, 1658, 1666, 1675, 1758, 1800, 1901, 1905, 1912, 1992, 1999, 2013, 2209, 2214, 2234, 2250, 2281, 2304, 2355, 2388, 2437, 2471, 2500, 2522, 2547, 2589, 2590, 2602, 2608, 2610, 2634, 2647, 2678, 2682, 2720, 2739, 2745, 2754, 2772, 2790, 2810, 2819, 2822, 2830, 2846, 2854, 2856, 2865, 2875, 2886, 2917, 2968, 2981, 2991, 3009, 3024, 3107, 3120, 3141, 3151, 3238, 3273, 3280, 3303, 3335, 3354, 3374, 3395, 3396, 3416, 3478, 3519, 3535, 3544, 3557, 3620, 3635, 3649, 3653, 3685, 3686, 3708, 3743, 3751, 3754, 3766, 3774, 3775, 3783]
Topluluk 7: [28, 90, 165, 170, 173, 199, 216, 234, 269, 283, 289, 295, 346, 376, 396, 423, 431, 439, 445, 453, 457, 463, 469, 471, 476, 502, 508, 530, 547, 570, 574, 575, 576, 578, 589, 608, 612, 665, 679, 693, 717, 721, 759, 760, 774, 793, 806, 808, 809, 824, 838, 841, 865, 875, 879, 885, 895, 920, 932, 934, 943, 973, 999, 1012, 1013, 1030, 1031, 1042, 1045, 1048, 1053, 1055, 1056, 1061, 1100, 1106, 1125, 1126, 1160, 1173, 1189, 1201, 1224, 1226, 1242, 1244, 1260, 1262, 1269, 1277, 1280, 1281, 1293, 1296, 1333, 1349, 1364, 1367, 1377, 1378, 1400, 1408, 1410, 1434, 1436, 1444, 1445, 1451, 1518, 1555, 1569, 1572, 1600, 1607, 1608, 1610, 1620, 1625, 1639, 1643, 1645, 1694, 1728, 1731, 1738, 1746, 1752, 1762, 1781, 1811, 1827, 1828, 1846, 1875, 1887, 1916, 1921, 1929, 1931, 1932, 1941, 1959, 1964, 1972, 2006, 2023, 2024, 2027, 2030, 2036, 2046, 2056, 2063, 2064, 2117, 2132, 2147, 2151, 2175, 2178, 2181, 2184, 2194, 2203, 2229, 2241, 2264, 2282, 2284, 2294, 2310, 2315, 2316, 2331, 2334, 2347, 2359, 2408, 2418, 2419, 2420, 2432, 2444, 2456, 2463, 2468, 2472, 2478, 2501, 2510, 2520, 2525, 2537, 2545, 2546, 2559, 2561, 2563, 2583, 2607, 2621, 2623, 2624, 2626, 2627, 2631, 2689, 2690, 2693, 2707, 2712, 2743, 2751, 2758, 2779, 2786, 2802, 2804, 2817, 2823, 2843, 2848, 2851, 2859, 2869, 2882, 2883, 2892, 2932, 2936, 2940, 2950, 2952, 2970, 2982, 2987, 3005, 3029, 3041, 3057, 3065, 3076, 3094, 3122, 3133, 3149, 3150, 3157, 3166, 3176, 3185, 3197, 3204, 3218, 3233, 3235, 3261, 3262, 3294, 3300, 3305, 3309, 3315, 3334, 3338, 3351, 3377, 3379, 3391, 3392, 3413, 3415, 3420, 3426, 3428, 3432, 3440, 3457, 3459, 3468, 3471, 3511, 3515, 3522, 3523, 3536, 3547, 3548, 3560, 3565, 3596, 3600, 3641, 3648, 3657, 3668, 3692, 3703, 3715, 3725, 3727, 3729, 3735, 3752, 3756, 3763, 3767, 3784, 3788, 3794]
Topluluk 8: [72, 82, 91, 132, 161, 176, 188, 226, 238, 279, 313, 333, 342, 343, 384, 403, 404, 412, 446, 450, 526, 541, 587, 598, 603, 625, 627, 630, 633, 643, 649, 654, 698, 751, 766, 776, 822, 837, 844, 850, 872, 906, 946, 954, 959, 1028, 1071, 1096, 1116, 1120, 1123, 1154, 1167, 1193, 1200, 1220, 1227, 1231, 1233, 1234, 1253, 1271, 1273, 1290, 1306, 1332, 1347, 1354, 1355, 1362, 1390, 1404, 1409, 1468, 1490, 1494, 1496, 1503, 1506, 1521, 1538, 1543, 1585, 1615, 1627, 1628, 1630, 1654, 1657, 1686, 1704, 1705, 1718, 1719, 1733, 1736, 1754, 1770, 1774, 1784, 1823, 1835, 1863, 1873, 1876, 1891, 1936, 1951, 1961, 1994, 2003, 2047, 2054, 2060, 2087, 2096, 2130, 2183, 2201, 2204, 2212, 2276, 2296, 2317, 2327, 2348, 2364, 2367, 2391, 2410, 2412, 2435, 2465, 2469, 2483, 2488, 2489, 2493, 2521, 2527, 2543, 2574, 2579, 2584, 2614, 2629, 2636, 2675, 2683, 2684, 2711, 2714, 2746, 2798, 2801, 2808, 2833, 2858, 2876, 2900, 2973, 2980, 2986, 2989, 3021, 3031, 3063, 3067, 3082, 3118, 3127, 3136, 3148, 3156, 3162, 3171, 3306, 3310, 3311, 3318, 3322, 3323, 3324, 3330, 3352, 3363, 3406, 3423, 3430, 3434, 3446, 3447, 3497, 3499, 3525, 3530, 3540, 3553, 3579, 3656, 3659, 3684, 3687, 3690, 3732, 3758]
Topluluk 9: [109, 136, 246, 260, 278, 305, 315, 316, 338, 349, 365, 391, 499, 500, 509, 534, 561, 594, 602, 610, 638, 699, 735, 738, 757, 761, 894, 960, 978, 998, 1069, 1099, 1108, 1128, 1202, 1229, 1297, 1348, 1353, 1417, 1424, 1531, 1544, 1547, 1617, 1644, 1679, 1693, 1714, 1725, 1745, 1789, 1795, 1799, 1832, 1844, 1883, 1954, 1980, 1984, 2009, 2020, 2086, 2187, 2198, 2218, 2269, 2318, 2328, 2329, 2354, 2564, 2566, 2599, 2719, 2724, 2726, 2753, 2791, 2825, 2828, 2870, 2878, 2920, 2921, 2985, 3040, 3052, 3054, 3084, 3103, 3106, 3117, 3132, 3165, 3226, 3236, 3258, 3270, 3328, 3347, 3355, 3361, 3370, 3389, 3419, 3445, 3456, 3510, 3583, 3642, 3724, 3741, 3742, 3762, 3791, 3796, 3797, 3798, 3799]

In [28]:
import leidenalg
from igraph import Graph as igraph_Graph

# NetworkX grafını igraph'a çevirme
G_igraph = igraph_Graph.from_networkx(G)  # G, nx.Graph() nesnesi olmalı

# Leiden uygula
partition = leidenalg.find_partition(G_igraph,  leidenalg.ModularityVertexPartition)
partition = {node: partition.membership[i] for i, node in enumerate(G.nodes())}

In [30]:
# Hangi düğüm hangi kümede?
print("\nDüğümlerin Toplulukları:")
for node, community in partition.items():
    print(f"Düğüm {node} → Küme {community}")
print("modularity:", community_louvain.modularity(partition, G, weight='weight'))

Düğümlerin Toplulukları:
Düğüm 0 → Küme 4
Düğüm 1 → Küme 3
Düğüm 2 → Küme 2
Düğüm 3 → Küme 0
Düğüm 4 → Küme 0
Düğüm 5 → Küme 3
Düğüm 6 → Küme 0
Düğüm 7 → Küme 0
Düğüm 8 → Küme 1
Düğüm 9 → Küme 1
Düğüm 10 → Küme 3
Düğüm 11 → Küme 3
Düğüm 12 → Küme 4
Düğüm 13 → Küme 3
Düğüm 14 → Küme 8
Düğüm 15 → Küme 0
Düğüm 16 → Küme 0
Düğüm 17 → Küme 3
Düğüm 18 → Küme 3
Düğüm 19 → Küme 1
Düğüm 20 → Küme 2
Düğüm 21 → Küme 0
Düğüm 22 → Küme 3
Düğüm 23 → Küme 0
Düğüm 24 → Küme 3
Düğüm 25 → Küme 4
Düğüm 26 → Küme 2
Düğüm 27 → Küme 3
Düğüm 28 → Küme 0
Düğüm 29 → Küme 8
Düğüm 30 → Küme 0
Düğüm 31 → Küme 0
Düğüm 32 → Küme 1
Düğüm 33 → Küme 1
Düğüm 34 → Küme 3
Düğüm 35 → Küme 3
Düğüm 36 → Küme 3
Düğüm 37 → Küme 2
Düğüm 38 → Küme 0
Düğüm 39 → Küme 0
Düğüm 40 → Küme 4
Düğüm 41 → Küme 1
Düğüm 42 → Küme 3
Düğüm 43 → Küme 1
Düğüm 44 → Küme 1
Düğüm 45 → Küme 3
Düğüm 46 → Küme 4
Düğüm 47 → Küme 1
Düğüm 48 → Küme 3
Düğüm 49 → Küme 1
Düğüm 50 → Küme 3
Düğüm 51 → Küme 0
Düğüm 52 → Küme 3
Düğüm 53 → Küme 0
Düğüm 54 → Küme 0
Düğüm 55 → Küme 1
Düğüm 56 → Küme 0
Düğüm 57 → Küme 3
Düğüm 58 → Küme 3
Düğüm 59 → Küme 2
Düğüm 60 → Küme 8
Düğüm 61 → Küme 0
Düğüm 62 → Küme 8
Düğüm 63 → Küme 8
Düğüm 64 → Küme 0
Düğüm 65 → Küme 3
Düğüm 66 → Küme 1
Düğüm 67 → Küme 0
Düğüm 68 → Küme 0
Düğüm 69 → Küme 0
Düğüm 70 → Küme 1
Düğüm 71 → Küme 1
Düğüm 72 → Küme 5
Düğüm 73 → Küme 3
Düğüm 74 → Küme 0
Düğüm 75 → Küme 3
Düğüm 76 → Küme 8
Düğüm 77 → Küme 3
Düğüm 78 → Küme 4
Düğüm 79 → Küme 3
Düğüm 80 → Küme 1
Düğüm 81 → Küme 0
Düğüm 82 → Küme 5
Düğüm 83 → Küme 1
Düğüm 84 → Küme 8
Düğüm 85 → Küme 4
Düğüm 86 → Küme 2
Düğüm 87 → Küme 2
Düğüm 88 → Küme 8
Düğüm 89 → Küme 2
Düğüm 90 → Küme 7
Düğüm 91 → Küme 5
Düğüm 92 → Küme 0
Düğüm 93 → Küme 0
Düğüm 94 → Küme 3
Düğüm 95 → Küme 3
Düğüm 96 → Küme 4
Düğüm 97 → Küme 4
Düğüm 98 → Küme 3
Düğüm 99 → Küme 2
Düğüm 100 → Küme 0
Düğüm 101 → Küme 8
Düğüm 102 → Küme 2
Düğüm 103 → Küme 2
Düğüm 104 → Küme 3
Düğüm 105 → Küme 3
Düğüm 106 → Küme 0
Düğüm 107 → Küme 3
Düğüm 108 → Küme 1
Düğüm 109 → Küme 10
Düğüm 110 → Küme 1
Düğüm 111 → Küme 3
Düğüm 112 → Küme 2
Düğüm 113 → Küme 0
Düğüm 114 → Küme 2
Düğüm 115 → Küme 7
Düğüm 116 → Küme 2
Düğüm 117 → Küme 1
Düğüm 118 → Küme 7
Düğüm 119 → Küme 8
Düğüm 120 → Küme 2
Düğüm 121 → Küme 3
Düğüm 122 → Küme 3
Düğüm 123 → Küme 1
Düğüm 124 → Küme 3
Düğüm 125 → Küme 0
Düğüm 126 → Küme 3
Düğüm 127 → Küme 4
Düğüm 128 → Küme 1
Düğüm 129 → Küme 4
Düğüm 130 → Küme 0
Düğüm 131 → Küme 3
Düğüm 132 → Küme 5
Düğüm 133 → Küme 4
Düğüm 134 → Küme 4
Düğüm 135 → Küme 2
Düğüm 136 → Küme 1
Düğüm 137 → Küme 4
Düğüm 138 → Küme 0
Düğüm 139 → Küme 3
Düğüm 140 → Küme 1
Düğüm 141 → Küme 0
Düğüm 142 → Küme 1
Düğüm 143 → Küme 1
Düğüm 144 → Küme 2
Düğüm 145 → Küme 0
Düğüm 146 → Küme 0
Düğüm 147 → Küme 0
Düğüm 148 → Küme 0
Düğüm 149 → Küme 0
Düğüm 150 → Küme 4
Düğüm 151 → Küme 0
Düğüm 152 → Küme 8
Düğüm 153 → Küme 3
Düğüm 154 → Küme 3
Düğüm 155 → Küme 8
Düğüm 156 → Küme 4
Düğüm 157 → Küme 3
Düğüm 158 → Küme 3
Düğüm 159 → Küme 0
Düğüm 160 → Küme 0
Düğüm 161 → Küme 5
Düğüm 162 → Küme 1
Düğüm 163 → Küme 4
Düğüm 164 → Küme 3
Düğüm 165 → Küme 0
Düğüm 166 → Küme 2
Düğüm 167 → Küme 1
Düğüm 168 → Küme 3
Düğüm 169 → Küme 3
Düğüm 170 → Küme 7
Düğüm 171 → Küme 0
Düğüm 172 → Küme 3
Düğüm 173 → Küme 7
Düğüm 174 → Küme 3
Düğüm 175 → Küme 4
Düğüm 176 → Küme 5
Düğüm 177 → Küme 3
Düğüm 178 → Küme 3
Düğüm 179 → Küme 0
Düğüm 180 → Küme 0
Düğüm 181 → Küme 0
Düğüm 182 → Küme 1
Düğüm 183 → Küme 0
Düğüm 184 → Küme 4
Düğüm 185 → Küme 1
Düğüm 186 → Küme 1
Düğüm 187 → Küme 2
Düğüm 188 → Küme 5
Düğüm 189 → Küme 0
Düğüm 190 → Küme 0
Düğüm 191 → Küme 6
Düğüm 192 → Küme 0
Düğüm 193 → Küme 0
Düğüm 194 → Küme 0
Düğüm 195 → Küme 3
Düğüm 196 → Küme 3
Düğüm 197 → Küme 6
Düğüm 198 → Küme 8
Düğüm 199 → Küme 0
Düğüm 200 → Küme 0
Düğüm 201 → Küme 4
Düğüm 202 → Küme 3
Düğüm 203 → Küme 8
Düğüm 204 → Küme 0
Düğüm 205 → Küme 6
Düğüm 206 → Küme 2
Düğüm 207 → Küme 2
Düğüm 208 → Küme 1
Düğüm 209 → Küme 1
Düğüm 210 → Küme 4
Düğüm 211 → Küme 2
Düğüm 212 → Küme 6
Düğüm 213 → Küme 0
Düğüm 214 → Küme 2
Düğüm 215 → Küme 3
Düğüm 216 → Küme 0
Düğüm 217 → Küme 0
Düğüm 218 → Küme 1
Düğüm 219 → Küme 2
Düğüm 220 → Küme 3
Düğüm 221 → Küme 4
Düğüm 222 → Küme 1
Düğüm 223 → Küme 0
Düğüm 224 → Küme 0
Düğüm 225 → Küme 0
Düğüm 226 → Küme 5
Düğüm 227 → Küme 4
Düğüm 228 → Küme 1
Düğüm 229 → Küme 1
Düğüm 230 → Küme 0
Düğüm 231 → Küme 3
Düğüm 232 → Küme 1
Düğüm 233 → Küme 6
Düğüm 234 → Küme 7
Düğüm 235 → Küme 0
Düğüm 236 → Küme 0
Düğüm 237 → Küme 0
Düğüm 238 → Küme 5
Düğüm 239 → Küme 2
Düğüm 240 → Küme 0
Düğüm 241 → Küme 3
Düğüm 242 → Küme 0
Düğüm 243 → Küme 3
Düğüm 244 → Küme 3
Düğüm 245 → Küme 0
Düğüm 246 → Küme 7
Düğüm 247 → Küme 9
Düğüm 248 → Küme 0
Düğüm 249 → Küme 0
Düğüm 250 → Küme 4
Düğüm 251 → Küme 1
Düğüm 252 → Küme 1
Düğüm 253 → Küme 9
Düğüm 254 → Küme 0
Düğüm 255 → Küme 0
Düğüm 256 → Küme 0
Düğüm 257 → Küme 3
Düğüm 258 → Küme 3
Düğüm 259 → Küme 0
Düğüm 260 → Küme 1
Düğüm 261 → Küme 2
Düğüm 262 → Küme 1
Düğüm 263 → Küme 3
Düğüm 264 → Küme 2
Düğüm 265 → Küme 3
Düğüm 266 → Küme 3
Düğüm 267 → Küme 1
Düğüm 268 → Küme 2
Düğüm 269 → Küme 5
Düğüm 270 → Küme 1
Düğüm 271 → Küme 4
Düğüm 272 → Küme 0
Düğüm 273 → Küme 2
Düğüm 274 → Küme 4
Düğüm 275 → Küme 2
Düğüm 276 → Küme 0
Düğüm 277 → Küme 0
Düğüm 278 → Küme 1
Düğüm 279 → Küme 5
Düğüm 280 → Küme 6
Düğüm 281 → Küme 1
Düğüm 282 → Küme 2
Düğüm 283 → Küme 7
Düğüm 284 → Küme 2
Düğüm 285 → Küme 9
Düğüm 286 → Küme 4
Düğüm 287 → Küme 2
Düğüm 288 → Küme 1
Düğüm 289 → Küme 7
Düğüm 290 → Küme 1
Düğüm 291 → Küme 0
Düğüm 292 → Küme 3
Düğüm 293 → Küme 0
Düğüm 294 → Küme 0
Düğüm 295 → Küme 7
Düğüm 296 → Küme 3
Düğüm 297 → Küme 3
Düğüm 298 → Küme 3
Düğüm 299 → Küme 1
Düğüm 300 → Küme 7
Düğüm 301 → Küme 4
Düğüm 302 → Küme 1
Düğüm 303 → Küme 6
Düğüm 304 → Küme 1
Düğüm 305 → Küme 1
Düğüm 306 → Küme 2
Düğüm 307 → Küme 3
Düğüm 308 → Küme 1
Düğüm 309 → Küme 7
Düğüm 310 → Küme 0
Düğüm 311 → Küme 1
Düğüm 312 → Küme 1
Düğüm 313 → Küme 5
Düğüm 314 → Küme 8
Düğüm 315 → Küme 10
Düğüm 316 → Küme 1
Düğüm 317 → Küme 0
Düğüm 318 → Küme 0
Düğüm 319 → Küme 2
Düğüm 320 → Küme 5
Düğüm 321 → Küme 0
Düğüm 322 → Küme 9
Düğüm 323 → Küme 3
Düğüm 324 → Küme 2
Düğüm 325 → Küme 0
Düğüm 326 → Küme 3
Düğüm 327 → Küme 4
Düğüm 328 → Küme 3
Düğüm 329 → Küme 2
Düğüm 330 → Küme 9
Düğüm 331 → Küme 1
Düğüm 332 → Küme 1
Düğüm 333 → Küme 5
Düğüm 334 → Küme 1
Düğüm 335 → Küme 4
Düğüm 336 → Küme 3
Düğüm 337 → Küme 0
Düğüm 338 → Küme 10
Düğüm 339 → Küme 3
Düğüm 340 → Küme 1
Düğüm 341 → Küme 3
Düğüm 342 → Küme 5
Düğüm 343 → Küme 5
Düğüm 344 → Küme 4
Düğüm 345 → Küme 4
Düğüm 346 → Küme 5
Düğüm 347 → Küme 2
Düğüm 348 → Küme 4
Düğüm 349 → Küme 7
Düğüm 350 → Küme 2
Düğüm 351 → Küme 3
Düğüm 352 → Küme 1
Düğüm 353 → Küme 2
Düğüm 354 → Küme 4
Düğüm 355 → Küme 3
Düğüm 356 → Küme 4
Düğüm 357 → Küme 6
Düğüm 358 → Küme 1
Düğüm 359 → Küme 0
Düğüm 360 → Küme 1
Düğüm 361 → Küme 2
Düğüm 362 → Küme 6
Düğüm 363 → Küme 3
Düğüm 364 → Küme 4
Düğüm 365 → Küme 1
Düğüm 366 → Küme 6
Düğüm 367 → Küme 3
Düğüm 368 → Küme 2
Düğüm 369 → Küme 1
Düğüm 370 → Küme 8
Düğüm 371 → Küme 2
Düğüm 372 → Küme 0
Düğüm 373 → Küme 8
Düğüm 374 → Küme 0
Düğüm 375 → Küme 8
Düğüm 376 → Küme 0
Düğüm 377 → Küme 1
Düğüm 378 → Küme 4
Düğüm 379 → Küme 1
Düğüm 380 → Küme 0
Düğüm 381 → Küme 0
Düğüm 382 → Küme 2
Düğüm 383 → Küme 3
Düğüm 384 → Küme 5
Düğüm 385 → Küme 1
Düğüm 386 → Küme 1
Düğüm 387 → Küme 3
Düğüm 388 → Küme 2
Düğüm 389 → Küme 3
Düğüm 390 → Küme 0
Düğüm 391 → Küme 1
Düğüm 392 → Küme 2
Düğüm 393 → Küme 3
Düğüm 394 → Küme 2
Düğüm 395 → Küme 2
Düğüm 396 → Küme 5
Düğüm 397 → Küme 3
Düğüm 398 → Küme 2
Düğüm 399 → Küme 2
Düğüm 400 → Küme 3
Düğüm 401 → Küme 2
Düğüm 402 → Küme 7
Düğüm 403 → Küme 5
Düğüm 404 → Küme 5
Düğüm 405 → Küme 0
Düğüm 406 → Küme 9
Düğüm 407 → Küme 3
Düğüm 408 → Küme 1
Düğüm 409 → Küme 0
Düğüm 410 → Küme 0
Düğüm 411 → Küme 2
Düğüm 412 → Küme 5
Düğüm 413 → Küme 9
Düğüm 414 → Küme 0
Düğüm 415 → Küme 9
Düğüm 416 → Küme 0
Düğüm 417 → Küme 2
Düğüm 418 → Küme 0
Düğüm 419 → Küme 3
Düğüm 420 → Küme 2
Düğüm 421 → Küme 2
Düğüm 422 → Küme 2
Düğüm 423 → Küme 7
Düğüm 424 → Küme 1
Düğüm 425 → Küme 3
Düğüm 426 → Küme 4
Düğüm 427 → Küme 1
Düğüm 428 → Küme 0
Düğüm 429 → Küme 8
Düğüm 430 → Küme 0
Düğüm 431 → Küme 5
Düğüm 432 → Küme 3
Düğüm 433 → Küme 1
Düğüm 434 → Küme 0
Düğüm 435 → Küme 0
Düğüm 436 → Küme 2
Düğüm 437 → Küme 3
Düğüm 438 → Küme 1
Düğüm 439 → Küme 7
Düğüm 440 → Küme 1
Düğüm 441 → Küme 4
Düğüm 442 → Küme 1
Düğüm 443 → Küme 2
Düğüm 444 → Küme 1
Düğüm 445 → Küme 5
Düğüm 446 → Küme 5
Düğüm 447 → Küme 6
Düğüm 448 → Küme 1
Düğüm 449 → Küme 0
Düğüm 450 → Küme 5
Düğüm 451 → Küme 2
Düğüm 452 → Küme 1
Düğüm 453 → Küme 0
Düğüm 454 → Küme 3
Düğüm 455 → Küme 4
Düğüm 456 → Küme 1
Düğüm 457 → Küme 7
Düğüm 458 → Küme 1
Düğüm 459 → Küme 6
Düğüm 460 → Küme 6
Düğüm 461 → Küme 4
Düğüm 462 → Küme 0
Düğüm 463 → Küme 5
Düğüm 464 → Küme 1
Düğüm 465 → Küme 2
Düğüm 466 → Küme 6
Düğüm 467 → Küme 3
Düğüm 468 → Küme 1
Düğüm 469 → Küme 7
Düğüm 470 → Küme 0
Düğüm 471 → Küme 7
Düğüm 472 → Küme 0
Düğüm 473 → Küme 0
Düğüm 474 → Küme 3
Düğüm 475 → Küme 2
Düğüm 476 → Küme 5
Düğüm 477 → Küme 1
Düğüm 478 → Küme 0
Düğüm 479 → Küme 2
Düğüm 480 → Küme 0
Düğüm 481 → Küme 8
Düğüm 482 → Küme 3
Düğüm 483 → Küme 0
Düğüm 484 → Küme 4
Düğüm 485 → Küme 3
Düğüm 486 → Küme 3
Düğüm 487 → Küme 0
Düğüm 488 → Küme 1
Düğüm 489 → Küme 1
Düğüm 490 → Küme 3
Düğüm 491 → Küme 2
Düğüm 492 → Küme 3
Düğüm 493 → Küme 6
Düğüm 494 → Küme 4
Düğüm 495 → Küme 2
Düğüm 496 → Küme 1
Düğüm 497 → Küme 8
Düğüm 498 → Küme 0
Düğüm 499 → Küme 1
Düğüm 500 → Küme 7
Düğüm 501 → Küme 3
Düğüm 502 → Küme 0
Düğüm 503 → Küme 1
Düğüm 504 → Küme 0
Düğüm 505 → Küme 3
Düğüm 506 → Küme 0
Düğüm 507 → Küme 0
Düğüm 508 → Küme 7
Düğüm 509 → Küme 10
Düğüm 510 → Küme 0
Düğüm 511 → Küme 0
Düğüm 512 → Küme 8
Düğüm 513 → Küme 1
Düğüm 514 → Küme 1
Düğüm 515 → Küme 1
Düğüm 516 → Küme 9
Düğüm 517 → Küme 2
Düğüm 518 → Küme 2
Düğüm 519 → Küme 8
Düğüm 520 → Küme 4
Düğüm 521 → Küme 2
Düğüm 522 → Küme 1
Düğüm 523 → Küme 1
Düğüm 524 → Küme 2
Düğüm 525 → Küme 2
Düğüm 526 → Küme 5
Düğüm 527 → Küme 2
Düğüm 528 → Küme 3
Düğüm 529 → Küme 0
Düğüm 530 → Küme 0
Düğüm 531 → Küme 1
Düğüm 532 → Küme 8
Düğüm 533 → Küme 3
Düğüm 534 → Küme 1
Düğüm 535 → Küme 1
Düğüm 536 → Küme 1
Düğüm 537 → Küme 0
Düğüm 538 → Küme 0
Düğüm 539 → Küme 1
Düğüm 540 → Küme 3
Düğüm 541 → Küme 5
Düğüm 542 → Küme 3
Düğüm 543 → Küme 2
Düğüm 544 → Küme 3
Düğüm 545 → Küme 2
Düğüm 546 → Küme 0
Düğüm 547 → Küme 0
Düğüm 548 → Küme 0
Düğüm 549 → Küme 3
Düğüm 550 → Küme 4
Düğüm 551 → Küme 1
Düğüm 552 → Küme 9
Düğüm 553 → Küme 2
Düğüm 554 → Küme 4
Düğüm 555 → Küme 2
Düğüm 556 → Küme 2
Düğüm 557 → Küme 1
Düğüm 558 → Küme 2
Düğüm 559 → Küme 1
Düğüm 560 → Küme 8
Düğüm 561 → Küme 10
Düğüm 562 → Küme 0
Düğüm 563 → Küme 0
Düğüm 564 → Küme 4
Düğüm 565 → Küme 6
Düğüm 566 → Küme 8
Düğüm 567 → Küme 2
Düğüm 568 → Küme 0
Düğüm 569 → Küme 8
Düğüm 570 → Küme 5
Düğüm 571 → Küme 0
Düğüm 572 → Küme 0
Düğüm 573 → Küme 1
Düğüm 574 → Küme 2
Düğüm 575 → Küme 7
Düğüm 576 → Küme 3
Düğüm 577 → Küme 2
Düğüm 578 → Küme 7
Düğüm 579 → Küme 0
Düğüm 580 → Küme 0
Düğüm 581 → Küme 9
Düğüm 582 → Küme 3
Düğüm 583 → Küme 8
Düğüm 584 → Küme 3
Düğüm 585 → Küme 1
Düğüm 586 → Küme 2
Düğüm 587 → Küme 5
Düğüm 588 → Küme 1
Düğüm 589 → Küme 7
Düğüm 590 → Küme 4
Düğüm 591 → Küme 0
Düğüm 592 → Küme 2
Düğüm 593 → Küme 0
Düğüm 594 → Küme 7
Düğüm 595 → Küme 0
Düğüm 596 → Küme 0
Düğüm 597 → Küme 2
Düğüm 598 → Küme 5
Düğüm 599 → Küme 3
Düğüm 600 → Küme 1
Düğüm 601 → Küme 3
Düğüm 602 → Küme 1
Düğüm 603 → Küme 5
Düğüm 604 → Küme 3
Düğüm 605 → Küme 3
Düğüm 606 → Küme 2
Düğüm 607 → Küme 0
Düğüm 608 → Küme 7
Düğüm 609 → Küme 0
Düğüm 610 → Küme 7
Düğüm 611 → Küme 4
Düğüm 612 → Küme 1
Düğüm 613 → Küme 2
Düğüm 614 → Küme 2
Düğüm 615 → Küme 3
Düğüm 616 → Küme 0
Düğüm 617 → Küme 2
Düğüm 618 → Küme 1
Düğüm 619 → Küme 1
Düğüm 620 → Küme 3
Düğüm 621 → Küme 0
Düğüm 622 → Küme 0
Düğüm 623 → Küme 3
Düğüm 624 → Küme 0
Düğüm 625 → Küme 5
Düğüm 626 → Küme 6
Düğüm 627 → Küme 5
Düğüm 628 → Küme 3
Düğüm 629 → Küme 2
Düğüm 630 → Küme 5
Düğüm 631 → Küme 2
Düğüm 632 → Küme 2
Düğüm 633 → Küme 5
Düğüm 634 → Küme 1
Düğüm 635 → Küme 4
Düğüm 636 → Küme 0
Düğüm 637 → Küme 4
Düğüm 638 → Küme 1
Düğüm 639 → Küme 4
Düğüm 640 → Küme 4
Düğüm 641 → Küme 0
Düğüm 642 → Küme 6
Düğüm 643 → Küme 5
Düğüm 644 → Küme 3
Düğüm 645 → Küme 7
Düğüm 646 → Küme 8
Düğüm 647 → Küme 9
Düğüm 648 → Küme 3
Düğüm 649 → Küme 5
Düğüm 650 → Küme 8
Düğüm 651 → Küme 0
Düğüm 652 → Küme 0
Düğüm 653 → Küme 4
Düğüm 654 → Küme 5
Düğüm 655 → Küme 2
Düğüm 656 → Küme 2
Düğüm 657 → Küme 2
Düğüm 658 → Küme 0
Düğüm 659 → Küme 4
Düğüm 660 → Küme 6
Düğüm 661 → Küme 0
Düğüm 662 → Küme 1
Düğüm 663 → Küme 3
Düğüm 664 → Küme 6
Düğüm 665 → Küme 0
Düğüm 666 → Küme 0
Düğüm 667 → Küme 0
Düğüm 668 → Küme 1
Düğüm 669 → Küme 4
Düğüm 670 → Küme 1
Düğüm 671 → Küme 3
Düğüm 672 → Küme 0
Düğüm 673 → Küme 3
Düğüm 674 → Küme 0
Düğüm 675 → Küme 2
Düğüm 676 → Küme 4
Düğüm 677 → Küme 6
Düğüm 678 → Küme 4
Düğüm 679 → Küme 0
Düğüm 680 → Küme 0
Düğüm 681 → Küme 4
Düğüm 682 → Küme 3
Düğüm 683 → Küme 8
Düğüm 684 → Küme 0
Düğüm 685 → Küme 0
Düğüm 686 → Küme 2
Düğüm 687 → Küme 2
Düğüm 688 → Küme 1
Düğüm 689 → Küme 4
Düğüm 690 → Küme 6
Düğüm 691 → Küme 4
Düğüm 692 → Küme 3
Düğüm 693 → Küme 7
Düğüm 694 → Küme 0
Düğüm 695 → Küme 3
Düğüm 696 → Küme 1
Düğüm 697 → Küme 0
Düğüm 698 → Küme 5
Düğüm 699 → Küme 7
Düğüm 700 → Küme 8
Düğüm 701 → Küme 0
Düğüm 702 → Küme 2
Düğüm 703 → Küme 1
Düğüm 704 → Küme 8
Düğüm 705 → Küme 1
Düğüm 706 → Küme 1
Düğüm 707 → Küme 3
Düğüm 708 → Küme 9
Düğüm 709 → Küme 3
Düğüm 710 → Küme 2
Düğüm 711 → Küme 2
Düğüm 712 → Küme 0
Düğüm 713 → Küme 3
Düğüm 714 → Küme 6
Düğüm 715 → Küme 2
Düğüm 716 → Küme 0
Düğüm 717 → Küme 7
Düğüm 718 → Küme 4
Düğüm 719 → Küme 0
Düğüm 720 → Küme 1
Düğüm 721 → Küme 7
Düğüm 722 → Küme 0
Düğüm 723 → Küme 0
Düğüm 724 → Küme 1
Düğüm 725 → Küme 9
Düğüm 726 → Küme 0
Düğüm 727 → Küme 0
Düğüm 728 → Küme 8
Düğüm 729 → Küme 2
Düğüm 730 → Küme 1
Düğüm 731 → Küme 2
Düğüm 732 → Küme 3
Düğüm 733 → Küme 8
Düğüm 734 → Küme 3
Düğüm 735 → Küme 1
Düğüm 736 → Küme 0
Düğüm 737 → Küme 1
Düğüm 738 → Küme 10
Düğüm 739 → Küme 8
Düğüm 740 → Küme 2
Düğüm 741 → Küme 0
Düğüm 742 → Küme 0
Düğüm 743 → Küme 3
Düğüm 744 → Küme 4
Düğüm 745 → Küme 3
Düğüm 746 → Küme 4
Düğüm 747 → Küme 7
Düğüm 748 → Küme 4
Düğüm 749 → Küme 1
Düğüm 750 → Küme 3
Düğüm 751 → Küme 5
Düğüm 752 → Küme 7
Düğüm 753 → Küme 2
Düğüm 754 → Küme 3
Düğüm 755 → Küme 2
Düğüm 756 → Küme 0
Düğüm 757 → Küme 10
Düğüm 758 → Küme 6
Düğüm 759 → Küme 7
Düğüm 760 → Küme 0
Düğüm 761 → Küme 10
Düğüm 762 → Küme 2
Düğüm 763 → Küme 3
Düğüm 764 → Küme 1
Düğüm 765 → Küme 2
Düğüm 766 → Küme 5
Düğüm 767 → Küme 0
Düğüm 768 → Küme 0
Düğüm 769 → Küme 1
Düğüm 770 → Küme 4
Düğüm 771 → Küme 3
Düğüm 772 → Küme 0
Düğüm 773 → Küme 0
Düğüm 774 → Küme 7
Düğüm 775 → Küme 0
Düğüm 776 → Küme 5
Düğüm 777 → Küme 0
Düğüm 778 → Küme 0
Düğüm 779 → Küme 4
Düğüm 780 → Küme 3
Düğüm 781 → Küme 1
Düğüm 782 → Küme 1
Düğüm 783 → Küme 2
Düğüm 784 → Küme 0
Düğüm 785 → Küme 3
Düğüm 786 → Küme 1
Düğüm 787 → Küme 3
Düğüm 788 → Küme 1
Düğüm 789 → Küme 8
Düğüm 790 → Küme 0
Düğüm 791 → Küme 3
Düğüm 792 → Küme 3
Düğüm 793 → Küme 5
Düğüm 794 → Küme 2
Düğüm 795 → Küme 3
Düğüm 796 → Küme 6
Düğüm 797 → Küme 0
Düğüm 798 → Küme 3
Düğüm 799 → Küme 1
Düğüm 800 → Küme 0
Düğüm 801 → Küme 4
Düğüm 802 → Küme 2
Düğüm 803 → Küme 3
Düğüm 804 → Küme 2
Düğüm 805 → Küme 9
Düğüm 806 → Küme 7
Düğüm 807 → Küme 0
Düğüm 808 → Küme 7
Düğüm 809 → Küme 0
Düğüm 810 → Küme 3
Düğüm 811 → Küme 8
Düğüm 812 → Küme 0
Düğüm 813 → Küme 2
Düğüm 814 → Küme 0
Düğüm 815 → Küme 3
Düğüm 816 → Küme 4
Düğüm 817 → Küme 0
Düğüm 818 → Küme 1
Düğüm 819 → Küme 4
Düğüm 820 → Küme 1
Düğüm 821 → Küme 6
Düğüm 822 → Küme 5
Düğüm 823 → Küme 2
Düğüm 824 → Küme 7
Düğüm 825 → Küme 2
Düğüm 826 → Küme 4
Düğüm 827 → Küme 0
Düğüm 828 → Küme 3
Düğüm 829 → Küme 8
Düğüm 830 → Küme 1
Düğüm 831 → Küme 6
Düğüm 832 → Küme 0
Düğüm 833 → Küme 3
Düğüm 834 → Küme 0
Düğüm 835 → Küme 6
Düğüm 836 → Küme 2
Düğüm 837 → Küme 5
Düğüm 838 → Küme 7
Düğüm 839 → Küme 2
Düğüm 840 → Küme 3
Düğüm 841 → Küme 5
Düğüm 842 → Küme 6
Düğüm 843 → Küme 3
Düğüm 844 → Küme 5
Düğüm 845 → Küme 0
Düğüm 846 → Küme 2
Düğüm 847 → Küme 8
Düğüm 848 → Küme 7
Düğüm 849 → Küme 3
Düğüm 850 → Küme 5
Düğüm 851 → Küme 6
Düğüm 852 → Küme 8
Düğüm 853 → Küme 6
Düğüm 854 → Küme 0
Düğüm 855 → Küme 4
Düğüm 856 → Küme 4
Düğüm 857 → Küme 3
Düğüm 858 → Küme 2
Düğüm 859 → Küme 3
Düğüm 860 → Küme 3
Düğüm 861 → Küme 1
Düğüm 862 → Küme 1
Düğüm 863 → Küme 3
Düğüm 864 → Küme 0
Düğüm 865 → Küme 5
Düğüm 866 → Küme 2
Düğüm 867 → Küme 6
Düğüm 868 → Küme 2
Düğüm 869 → Küme 1
Düğüm 870 → Küme 0
Düğüm 871 → Küme 4
Düğüm 872 → Küme 5
Düğüm 873 → Küme 4
Düğüm 874 → Küme 1
Düğüm 875 → Küme 0
Düğüm 876 → Küme 0
Düğüm 877 → Küme 0
Düğüm 878 → Küme 2
Düğüm 879 → Küme 5
Düğüm 880 → Küme 0
Düğüm 881 → Küme 8
Düğüm 882 → Küme 2
Düğüm 883 → Küme 8
Düğüm 884 → Küme 1
Düğüm 885 → Küme 7
Düğüm 886 → Küme 4
Düğüm 887 → Küme 2
Düğüm 888 → Küme 0
Düğüm 889 → Küme 0
Düğüm 890 → Küme 1
Düğüm 891 → Küme 6
Düğüm 892 → Küme 2
Düğüm 893 → Küme 8
Düğüm 894 → Küme 1
Düğüm 895 → Küme 10
Düğüm 896 → Küme 0
Düğüm 897 → Küme 0
Düğüm 898 → Küme 3
Düğüm 899 → Küme 4
Düğüm 900 → Küme 3
Düğüm 901 → Küme 0
Düğüm 902 → Küme 2
Düğüm 903 → Küme 3
Düğüm 904 → Küme 4
Düğüm 905 → Küme 1
Düğüm 906 → Küme 5
Düğüm 907 → Küme 9
Düğüm 908 → Küme 8
Düğüm 909 → Küme 3
Düğüm 910 → Küme 3
Düğüm 911 → Küme 1
Düğüm 912 → Küme 2
Düğüm 913 → Küme 9
Düğüm 914 → Küme 6
Düğüm 915 → Küme 4
Düğüm 916 → Küme 0
Düğüm 917 → Küme 4
Düğüm 918 → Küme 0
Düğüm 919 → Küme 1
Düğüm 920 → Küme 7
Düğüm 921 → Küme 2
Düğüm 922 → Küme 3
Düğüm 923 → Küme 2
Düğüm 924 → Küme 6
Düğüm 925 → Küme 8
Düğüm 926 → Küme 3
Düğüm 927 → Küme 1
Düğüm 928 → Küme 4
Düğüm 929 → Küme 1
Düğüm 930 → Küme 1
Düğüm 931 → Küme 0
Düğüm 932 → Küme 5
Düğüm 933 → Küme 0
Düğüm 934 → Küme 1
Düğüm 935 → Küme 2
Düğüm 936 → Küme 0
Düğüm 937 → Küme 4
Düğüm 938 → Küme 4
Düğüm 939 → Küme 0
Düğüm 940 → Küme 2
Düğüm 941 → Küme 8
Düğüm 942 → Küme 8
Düğüm 943 → Küme 5
Düğüm 944 → Küme 0
Düğüm 945 → Küme 1
Düğüm 946 → Küme 5
Düğüm 947 → Küme 0
Düğüm 948 → Küme 0
Düğüm 949 → Küme 8
Düğüm 950 → Küme 3
Düğüm 951 → Küme 0
Düğüm 952 → Küme 1
Düğüm 953 → Küme 6
Düğüm 954 → Küme 5
Düğüm 955 → Küme 8
Düğüm 956 → Küme 1
Düğüm 957 → Küme 0
Düğüm 958 → Küme 2
Düğüm 959 → Küme 5
Düğüm 960 → Küme 1
Düğüm 961 → Küme 1
Düğüm 962 → Küme 4
Düğüm 963 → Küme 2
Düğüm 964 → Küme 4
Düğüm 965 → Küme 3
Düğüm 966 → Küme 4
Düğüm 967 → Küme 6
Düğüm 968 → Küme 3
Düğüm 969 → Küme 0
Düğüm 970 → Küme 3
Düğüm 971 → Küme 8
Düğüm 972 → Küme 3
Düğüm 973 → Küme 7
Düğüm 974 → Küme 0
Düğüm 975 → Küme 6
Düğüm 976 → Küme 1
Düğüm 977 → Küme 1
Düğüm 978 → Küme 10
Düğüm 979 → Küme 0
Düğüm 980 → Küme 6
Düğüm 981 → Küme 7
Düğüm 982 → Küme 1
Düğüm 983 → Küme 4
Düğüm 984 → Küme 1
Düğüm 985 → Küme 6
Düğüm 986 → Küme 1
Düğüm 987 → Küme 6
Düğüm 988 → Küme 1
Düğüm 989 → Küme 4
Düğüm 990 → Küme 8
Düğüm 991 → Küme 3
Düğüm 992 → Küme 8
Düğüm 993 → Küme 3
Düğüm 994 → Küme 6
Düğüm 995 → Küme 3
Düğüm 996 → Küme 3
Düğüm 997 → Küme 1
Düğüm 998 → Küme 10
Düğüm 999 → Küme 7
Düğüm 1000 → Küme 2
Düğüm 1001 → Küme 2
Düğüm 1002 → Küme 4
Düğüm 1003 → Küme 4
Düğüm 1004 → Küme 1
Düğüm 1005 → Küme 1
Düğüm 1006 → Küme 3
Düğüm 1007 → Küme 0
Düğüm 1008 → Küme 1
Düğüm 1009 → Küme 4
Düğüm 1010 → Küme 0
Düğüm 1011 → Küme 1
Düğüm 1012 → Küme 7
Düğüm 1013 → Küme 7
Düğüm 1014 → Küme 1
Düğüm 1015 → Küme 2
Düğüm 1016 → Küme 3
Düğüm 1017 → Küme 6
Düğüm 1018 → Küme 2
Düğüm 1019 → Küme 1
Düğüm 1020 → Küme 1
Düğüm 1021 → Küme 1
Düğüm 1022 → Küme 6
Düğüm 1023 → Küme 0
Düğüm 1024 → Küme 4
Düğüm 1025 → Küme 1
Düğüm 1026 → Küme 0
Düğüm 1027 → Küme 3
Düğüm 1028 → Küme 1
Düğüm 1029 → Küme 2
Düğüm 1030 → Küme 0
Düğüm 1031 → Küme 7
Düğüm 1032 → Küme 8
Düğüm 1033 → Küme 2
Düğüm 1034 → Küme 2
Düğüm 1035 → Küme 6
Düğüm 1036 → Küme 2
Düğüm 1037 → Küme 4
Düğüm 1038 → Küme 4
Düğüm 1039 → Küme 8
Düğüm 1040 → Küme 8
Düğüm 1041 → Küme 4
Düğüm 1042 → Küme 7
Düğüm 1043 → Küme 9
Düğüm 1044 → Küme 8
Düğüm 1045 → Küme 5
Düğüm 1046 → Küme 1
Düğüm 1047 → Küme 3
Düğüm 1048 → Küme 7
Düğüm 1049 → Küme 8
Düğüm 1050 → Küme 3
Düğüm 1051 → Küme 4
Düğüm 1052 → Küme 8

In [33]:
import leidenalg
from igraph import Graph as igraph_Graph
from collections import defaultdict
import networkx as nx  # modularity hesaplamak için gerekli

# NetworkX grafını igraph'a çevirme
G_igraph = igraph_Graph.from_networkx(G)  # G, nx.Graph() nesnesi olmalı

# Ağırlık ekleme (eğer varsa)
if 'weight' in G.edges():
    G_igraph.es['weight'] = [G[u][v]['weight'] for u, v in G.edges()]

# Resolution ayarıyla Leiden uygula (0.5-0.8 arası deneyin)
partition = leidenalg.find_partition(
    G_igraph, 
    leidenalg.RBConfigurationVertexPartition, 
    resolution_parameter=0.3,
    weights='weight' if 'weight' in G_igraph.edge_attributes() else None
)

# Yeni yöntemle küme bilgilerini al
communities = defaultdict(set)
for node_idx, community_id in enumerate(partition.membership):
    node_name = G_igraph.vs[node_idx]['_nx_name']  # Orijinal düğüm ismini al
    communities[community_id].add(node_name)

# Küme sayısı ve boyutları
print(f"Toplam küme sayısı: {len(communities)}")
for comm_id, nodes in communities.items():
    print(f"Küme {comm_id}: {len(nodes)} düğüm")

# Modularity hesapla ve yazdır
mod = partition.modularity
print(f"\nModularity değeri: {mod:.4f}")

# NetworkX ile modularity hesaplama alternatifi:
# nx_communities = [nodes for nodes in communities.values()]
# mod_nx = nx.algorithms.community.quality.modularity(G, nx_communities, weight='weight')
# print(f"NetworkX modularity: {mod_nx:.4f}")

Toplam küme sayısı: 15
Küme 2: 696 düğüm
Küme 0: 1816 düğüm
Küme 1: 1155 düğüm
Küme 3: 77 düğüm
Küme 4: 3 düğüm
Küme 6: 2 düğüm
Küme 7: 2 düğüm
Küme 5: 3 düğüm
Küme 10: 2 düğüm
Küme 11: 2 düğüm
Küme 12: 2 düğüm
Küme 13: 2 düğüm
Küme 8: 2 düğüm
Küme 14: 2 düğüm
Küme 9: 2 düğüm

Modularity değeri: 0.4210

In [35]:
# NetworkX ile modularity hesaplama alternatifi:
nx_communities = [nodes for nodes in communities.values()]
mod_nx = nx.algorithms.community.quality.modularity(G, nx_communities, weight='weight')
print(f"NetworkX modularity: {mod_nx:.4f}")

NetworkX modularity: 0.4876

In [37]:
subgraphs = []
for comm_id, nodes in communities.items():
    # Alt grafı oluştur (G'nin alt kümesi)
    subgraph = G.subgraph(nodes).copy()
    subgraphs.append(subgraph)
    
    # İsterseniz burada alt grafları kaydedebilir veya analiz edebilirsiniz
    print(f"Topluluk {comm_id} - Düğüm sayısı: {subgraph.number_of_nodes()}, Kenar sayısı: {subgraph.number_of_edges()}")

Topluluk 2 - Düğüm sayısı: 696, Kenar sayısı: 7062
Topluluk 0 - Düğüm sayısı: 1816, Kenar sayısı: 28182
Topluluk 1 - Düğüm sayısı: 1155, Kenar sayısı: 12571
Topluluk 3 - Düğüm sayısı: 77, Kenar sayısı: 426
Topluluk 4 - Düğüm sayısı: 3, Kenar sayısı: 2
Topluluk 6 - Düğüm sayısı: 2, Kenar sayısı: 1
Topluluk 7 - Düğüm sayısı: 2, Kenar sayısı: 1
Topluluk 5 - Düğüm sayısı: 3, Kenar sayısı: 3
Topluluk 10 - Düğüm sayısı: 2, Kenar sayısı: 1
Topluluk 11 - Düğüm sayısı: 2, Kenar sayısı: 1
Topluluk 12 - Düğüm sayısı: 2, Kenar sayısı: 1
Topluluk 13 - Düğüm sayısı: 2, Kenar sayısı: 1
Topluluk 8 - Düğüm sayısı: 2, Kenar sayısı: 1
Topluluk 14 - Düğüm sayısı: 2, Kenar sayısı: 1
Topluluk 9 - Düğüm sayısı: 2, Kenar sayısı: 1

In [42]:
import networkx as nx

# Leiden ile oluşturulmuş ilk alt ağı al
subgraphx = subgraphs[0]

# Tüm merkezilik ölçütlerini hesapla (ağırlıklı versiyonlar)
weight_param = 'weight' if 'weight' in subgraphx.edges() else None

centrality_metrics = {
    "Degree Centrality": nx.degree_centrality(subgraphx),
    "Betweenness Centrality": nx.betweenness_centrality(subgraphx, weight=weight_param),
    "Closeness Centrality": nx.closeness_centrality(subgraphx, distance=weight_param),
    "PageRank": nx.pagerank(subgraphx, weight=weight_param),
    "Authority (HITS)": nx.hits(subgraphx)[1],  # Sadece authority skorları
    "Eigenvector Centrality": nx.eigenvector_centrality(subgraphx, weight=weight_param, max_iter=1000)
}

# Her metrik için ilk 5 düğümü yazdır
for metric_name, scores in centrality_metrics.items():
    sorted_nodes = sorted(scores.items(), key=lambda x: -x[1])[:20]  # En yüksek 5 değer
    
    print(f"\n{metric_name} - Top 5:")
    for rank, (node, score) in enumerate(sorted_nodes, 1):
        print(f"{rank}. {node}: {[key for key, value in skill_to_id.items() if value == str(node)]}: {score:.4f}")

# Ekstra: Weighted Degree (Ağırlıklı derece) için
if weight_param:
    weighted_degrees = {node: sum(data['weight'] for _, _, data in subgraphx.edges(node, data=True)) 
                       for node in subgraphx.nodes()}
    
    print("\nWeighted Degree - Top 5:")
    for rank, (node, degree) in enumerate(sorted(weighted_degrees.items(), key=lambda x: -x[1])[:20], 1):
        print(f"{rank}. {node}: {degree:.2f}")

Degree Centrality - Top 5:
1. 0: ['Graphic Design']: 0.4791
2. 12: ['Adobe Photoshop']: 0.3568
3. 25: ['Adobe Illustrator']: 0.3381
4. 46: ['Illustration']: 0.2719
5. 72: ['3D Modeling']: 0.2158
6. 14: ['Video Editing']: 0.2101
7. 82: ['3D Design']: 0.1957
8. 40: ['Logo Design']: 0.1928
9. 91: ['3D Rendering']: 0.1813
10. 29: ['Video Production']: 0.1741
11. 62: ['Adobe After Effects']: 0.1640
12. 85: ['Animation']: 0.1583
13. 78: ['Photo Editing']: 0.1554
14. 137: ['Infographic']: 0.1540
15. 163: ['Character Design']: 0.1410
16. 129: ['Layout Design']: 0.1367
17. 134: ['Adobe InDesign']: 0.1338
18. 96: ['Social Media Imagery']: 0.1324
19. 132: ['Architectural Design']: 0.1324
20. 161: ['Autodesk AutoCAD']: 0.1309

Betweenness Centrality - Top 5:
1. 0: ['Graphic Design']: 0.2576
2. 12: ['Adobe Photoshop']: 0.1147
3. 25: ['Adobe Illustrator']: 0.0918
4. 72: ['3D Modeling']: 0.0807
5. 14: ['Video Editing']: 0.0591
6. 46: ['Illustration']: 0.0561
7. 82: ['3D Design']: 0.0526
8. 161: ['Autodesk AutoCAD']: 0.0478
9. 91: ['3D Rendering']: 0.0377
10. 29: ['Video Production']: 0.0350
11. 62: ['Adobe After Effects']: 0.0286
12. 78: ['Photo Editing']: 0.0252
13. 85: ['Animation']: 0.0250
14. 132: ['Architectural Design']: 0.0249
15. 40: ['Logo Design']: 0.0240
16. 344: ['Clothing']: 0.0189
17. 101: ['Audio Editing']: 0.0184
18. 279: ['Product Design']: 0.0162
19. 76: ['Videography']: 0.0158
20. 343: ['Concept Design']: 0.0151

Closeness Centrality - Top 5:
1. 0: ['Graphic Design']: 0.6471
2. 12: ['Adobe Photoshop']: 0.5945
3. 25: ['Adobe Illustrator']: 0.5850
4. 46: ['Illustration']: 0.5516
5. 72: ['3D Modeling']: 0.5400
6. 82: ['3D Design']: 0.5359
7. 91: ['3D Rendering']: 0.5265
8. 14: ['Video Editing']: 0.5229
9. 40: ['Logo Design']: 0.5190
10. 62: ['Adobe After Effects']: 0.5122
11. 78: ['Photo Editing']: 0.5110
12. 85: ['Animation']: 0.5062
13. 29: ['Video Production']: 0.5040
14. 84: ['Motion Graphics']: 0.5040
15. 163: ['Character Design']: 0.5007
16. 137: ['Infographic']: 0.4979
17. 176: ['3D Animation']: 0.4971
18. 134: ['Adobe InDesign']: 0.4954
19. 96: ['Social Media Imagery']: 0.4915
20. 129: ['Layout Design']: 0.4887

PageRank - Top 5:
1. 0: ['Graphic Design']: 0.0216
2. 12: ['Adobe Photoshop']: 0.0149
3. 25: ['Adobe Illustrator']: 0.0147
4. 46: ['Illustration']: 0.0114
5. 72: ['3D Modeling']: 0.0107
6. 14: ['Video Editing']: 0.0095
7. 82: ['3D Design']: 0.0092
8. 91: ['3D Rendering']: 0.0083
9. 40: ['Logo Design']: 0.0081
10. 29: ['Video Production']: 0.0076
11. 161: ['Autodesk AutoCAD']: 0.0071
12. 78: ['Photo Editing']: 0.0067
13. 62: ['Adobe After Effects']: 0.0066
14. 85: ['Animation']: 0.0066
15. 132: ['Architectural Design']: 0.0064
16. 137: ['Infographic']: 0.0060
17. 129: ['Layout Design']: 0.0059
18. 76: ['Videography']: 0.0055
19. 163: ['Character Design']: 0.0055
20. 134: ['Adobe InDesign']: 0.0054

Authority (HITS) - Top 5:
1. 0: ['Graphic Design']: 0.0787
2. 12: ['Adobe Photoshop']: 0.0645
3. 25: ['Adobe Illustrator']: 0.0612
4. 40: ['Logo Design']: 0.0377
5. 46: ['Illustration']: 0.0355
6. 14: ['Video Editing']: 0.0341
7. 29: ['Video Production']: 0.0286
8. 62: ['Adobe After Effects']: 0.0260
9. 63: ['Adobe Premiere Pro']: 0.0235
10. 97: ['Brand Identity & Guidelines']: 0.0228
11. 60: ['Video Post-Editing']: 0.0226
12. 96: ['Social Media Imagery']: 0.0212
13. 134: ['Adobe InDesign']: 0.0180
14. 78: ['Photo Editing']: 0.0172
15. 84: ['Motion Graphics']: 0.0156
16. 137: ['Infographic']: 0.0148
17. 150: ['Print Design']: 0.0130
18. 85: ['Animation']: 0.0129
19. 129: ['Layout Design']: 0.0125
20. 76: ['Videography']: 0.0121

Eigenvector Centrality - Top 5:
1. 0: ['Graphic Design']: 0.2567
2. 12: ['Adobe Photoshop']: 0.2270
3. 25: ['Adobe Illustrator']: 0.2138
4. 46: ['Illustration']: 0.1864
5. 40: ['Logo Design']: 0.1422
6. 137: ['Infographic']: 0.1316
7. 85: ['Animation']: 0.1268
8. 62: ['Adobe After Effects']: 0.1198
9. 163: ['Character Design']: 0.1195
10. 96: ['Social Media Imagery']: 0.1179
11. 14: ['Video Editing']: 0.1176
12. 78: ['Photo Editing']: 0.1131
13. 82: ['3D Design']: 0.1128
14. 175: ['Drawing']: 0.1118
15. 134: ['Adobe InDesign']: 0.1092
16. 72: ['3D Modeling']: 0.1067
17. 127: ['2D Animation']: 0.1061
18. 29: ['Video Production']: 0.1042
19. 129: ['Layout Design']: 0.1039
20. 455: ['Contemporary Style']: 0.1026